export const SONG_OPTIONS = [
    { id: 1, name: "Tell Your World", title_jp: "Tell Your World", title_hi: "Tell Your World", title_hangul: "텔 유어 월드", length: 123 },
    { id: 2, name: "로키", title_jp: "ロキ", title_hi: "ろき", title_hangul: "로키", length: 107 },
    { id: 3, name: "테오", title_jp: "テオ", title_hi: "てお", title_hangul: "데오", length: 116 },
    { id: 6, name: "히바나 -Reloaded-", title_jp: "ヒバナ -Reloaded-", title_hi: "ひばな -Reloaded-", title_hangul: "히바나 -리로디드-", length: 95 },
    { id: 8, name: "타임머신", title_jp: "タイムマシン", title_hi: "たいむましん", title_hangul: "다이무마신", length: 125 },
    { id: 10, name: "해피 신디사이저", title_jp: "ハッピーシンセサイザ", title_hi: "はっぴーしんせさいざ", title_hangul: "핫피신세사이자", length: 133 },
    { id: 11, name: "비바해피", title_jp: "ビバハピ", title_hi: "びばはぴ", title_hangul: "비바하피", length: 94 },
    { id: 13, name: "Nostalogic", title_jp: "Nostalogic", title_hi: "Nostalogic", title_hangul: "노스텔로직", length: 120 },
    { id: 15, name: "drop pop candy", title_jp: "drop pop candy", title_hi: "drop pop candy", title_hangul: "드롭 팝 캔디", length: 106 },
    { id: 18, name: "내일의 밤하늘 초계반", title_jp: "アスノヨゾラ哨戒班", title_hi: "あすのよぞらしょうかいはん", title_hangul: "아스노요조라쇼카이한", length: 128 },
    { id: 19, name: "샤를", title_jp: "シャルル", title_hi: "しゃるる", title_hangul: "샤루루", length: 104 },
    { id: 21, name: "탈법 록", title_jp: "脱法ロック", title_hi: "だっぽうろっく", title_hangul: "닷포롯쿠", length: 122 },
    { id: 22, name: "생명에게 미움받고 있어.", title_jp: "命に嫌われている", title_hi: "いのちにきらわれている", title_hangul: "이노치니키라와레테이루", length: 100 },
    { id: 26, name: "열등상등", title_jp: "劣等上等", title_hi: "れっとうじょうとう", title_hangul: "렛토조토", length: 99 },
    { id: 27, name: "Just Be Friends", title_jp: "Just Be Friends", title_hi: "Just Be Friends", title_hangul: "저스트 비 프렌즈", length: 133 },
    { id: 28, name: "닥터=펑크 비트", title_jp: "ドクター＝ファンクビート", title_hi: "どくたー＝ふぁんくびーと", title_hangul: "도쿠타＝후안쿠비토", length: 127 },
    { id: 36, name: "미라클 페인트", title_jp: "ミラクルペイント", title_hi: "みらくるぺいんと", title_hangul: "미라쿠루페인토", length: 146 },
    { id: 38, name: "브리키의 댄스", title_jp: "ブリキノダンス", title_hi: "ぶりきのだんす", title_hangul: "부리키노단스", length: 100 },
    { id: 41, name: "스위트 매직", title_jp: "スイートマジック", title_hi: "すいーとまじっく", title_hangul: "스이토마짓쿠", length: 149 },
    { id: 43, name: "넥스트 네스트", title_jp: "ネクストネスト", title_hi: "ねくすとねすと", title_hangul: "네쿠스토네스토", length: 127 },
    { id: 44, name: "Hand in Hand", title_jp: "Hand in Hand", title_hi: "Hand in Hand", title_hangul: "핸드 인 핸드", length: 124 },
    { id: 45, name: "39뮤직!", title_jp: "39みゅーじっく！", title_hi: "39みゅーじっく！", title_hangul: "39뮤짓쿠！", length: 119 },
    { id: 46, name: "그린라이츠 세레나데", title_jp: "グリーンライツ・セレナーデ", title_hi: "ぐりーんらいつ・せれなーで", title_hangul: "구린라이쓰・세레나데", length: 125 },
    { id: 47, name: "멜트", title_jp: "メルト", title_hi: "めると", title_hangul: "메루토", length: 182 },
    { id: 48, name: "월드 이즈 마인", title_jp: "ワールドイズマイン", title_hi: "わーるどいずまいん", title_hangul: "와루도이즈마인", length: 171 },
    { id: 49, name: "하츠네 미쿠의 소실", title_jp: "初音ミクの消失", title_hi: "はつねみくのしょうしつ", title_hangul: "하쓰네미쿠노쇼시쓰", length: 144 },
    { id: 50, name: "Blessing", title_jp: "Blessing", title_hi: "Blessing", title_hangul: "Blessing", length: 133 },
    { id: 51, name: "세상은 아직 시작조차 하지 않았어", title_jp: "セカイはまだ始まってすらいない", title_hi: "せかいはまだはじまってすらいない", title_hangul: "세카이하마다하지맛테스라이나이", length: 122 },
    { id: 52, name: "potato가 되어가", title_jp: "potatoになっていく", title_hi: "potatoになっていく", title_hangul: "감자니 낫테이쿠", length: 108 },
    { id: 54, name: "Ready Steady", title_jp: "Ready Steady", title_hi: "Ready Steady", title_hangul: "레디 스테디", length: 92 },
    { id: 55, name: "Forward", title_jp: "Forward", title_hi: "Forward", title_hangul: "포워드", length: 115 },
    { id: 57, name: "아이돌 신예대", title_jp: "アイドル新鋭隊", title_hi: "あいどるしんえいたい", title_hangul: "아이도루신에이타이", length: 106 },
    { id: 60, name: "후회한다 쓰고 미래", title_jp: "悔やむと書いてミライ", title_hi: "くやむとかいてみらい", title_hangul: "구야무토카이테미라이", length: 101 },
    { id: 61, name: "휴대연화", title_jp: "携帯恋話", title_hi: "けいたいこいばなし", title_hangul: "게이타이코이바나시", length: 139 },
    { id: 62, name: "잭팟 새드 걸", title_jp: "ジャックポットサッドガール", title_hi: "じゃっくぽっとさっどがーる", title_hangul: "잣쿠폿토삿도가루", length: 84 },
    { id: 63, name: "needLe", title_jp: "needLe", title_hi: "needLe", title_hangul: "니들", length: 115 },
    { id: 64, name: "스텔라", title_jp: "ステラ", title_hi: "すてら", title_hangul: "스테라", length: 133 },
    { id: 66, name: "하로/하와유", title_jp: "ハロ／ハワユ", title_hi: "はろ／はわゆ", title_hangul: "하로／하와유", length: 147 },
    { id: 67, name: "자상무색", title_jp: "自傷無色", title_hi: "じしょうむしょく", title_hangul: "지쇼무쇼쿠", length: 104 },
    { id: 68, name: "댄스 로봇 댄스", title_jp: "ダンスロボットダンス", title_hi: "だんすろぼっとだんす", title_hangul: "단스로봇토단스", length: 102 },
    { id: 69, name: "프래질", title_jp: "フラジール", title_hi: "ふらじーる", title_hangul: "후라지루", length: 124 },
    { id: 70, name: "멜티 랜드 나이트메어", title_jp: "メルティランドナイトメア", title_hi: "めるてぃらんどないとめあ", title_hangul: "메루테이란도나이토메아", length: 118 },
    { id: 71, name: "누덕누덕 스타카토", title_jp: "ツギハギスタッカート", title_hi: "つぎはぎすたっかーと", title_hangul: "쓰기하기스탓카토", length: 123 },
    { id: 72, name: "블레스 유어 브레스", title_jp: "ブレス・ユア・ブレス", title_hi: "ぶれす・ゆあ・ぶれす", title_hangul: "부레스・유아・부레스", length: 95 },
    { id: 73, name: "니아", title_jp: "ニア", title_hi: "にあ", title_hangul: "니아", length: 116 },
    { id: 74, name: "혼자 놀이 엔비", title_jp: "独りんぼエンヴィー", title_hi: "ひとりんぼえんゔぃー", title_hangul: "히토린보엔ヴ이", length: 75 },
    { id: 75, name: "갯나리 해저담", title_jp: "ウミユリ海底譚", title_hi: "うみゆりかいていたん", title_hangul: "우미유리카이테이탄", length: 103 },
    { id: 76, name: "세카이", title_jp: "セカイ", title_hi: "せかい", title_hangul: "세카이", length: 112 },
    { id: 77, name: "와 와 월드", title_jp: "ワーワーワールド", title_hi: "わーわーわーるど", title_hangul: "와와와루도", length: 109 },
    { id: 78, name: "모험의 서가 사라졌습니다!", title_jp: "ぼうけんのしょがきえました！", title_hi: "ぼうけんのしょがきえました！", title_hangul: "보켄노쇼가키에마시타！", length: 111 },
    { id: 81, name: "야화 디세이브", title_jp: "夜咄ディセイブ", title_hi: "よばなしでぃせいぶ", title_hangul: "요바나시데이세이부", length: 140 },
    { id: 82, name: "alive", title_jp: "alive", title_hi: "alive", title_hangul: "alive", length: 118 },
    { id: 83, name: "Gimme×Gimme", title_jp: "Gimme×Gimme", title_hi: "Gimme×Gimme", title_hangul: "김미x김미", length: 135 },
    { id: 84, name: "정키 나이트 타운 오케스트라", title_jp: "ジャンキーナイトタウンオーケストラ", title_hi: "じゃんきーないとたうんおーけすとら", title_hangul: "잔키나이토타운오케스토라", length: 142 },
    { id: 85, name: "Leia - Remind", title_jp: "Leia - Remind", title_hi: "Leia - Remind", title_hangul: "레이아 - 리마인드", length: 131 },
    { id: 86, name: "on the rocks", title_jp: "on the rocks", title_hi: "on the rocks", title_hangul: "온 더 록", length: 127 },
    { id: 87, name: "연애재판", title_jp: "恋愛裁判", title_hi: "れんあいさいばん", title_hangul: "렌아이사이반", length: 133 },
    { id: 88, name: "츄루리라·츄루리라·땃땃따!", title_jp: "チュルリラ・チュルリラ・ダッダッダ！", title_hi: "ちゅるりら・ちゅるりら・だっだっだ！", title_hangul: "주루리라・추루리라・닷닷다！", length: 143 },
    { id: 89, name: "Color of Drops", title_jp: "Color of Drops", title_hi: "Color of Drops", title_hangul: "컬러 오브 드롭스", length: 114 },
    { id: 90, name: "끝없이 잿빛으로", title_jp: "限りなく灰色へ", title_hi: "かぎりなくはいいろへ", title_hangul: "가기리나쿠하이로헤", length: 122 },
    { id: 91, name: "드라마투르기", title_jp: "ドラマツルギー", title_hi: "どらまつるぎー", title_hangul: "도라마쓰루기", length: 95 },
    { id: 92, name: "소녀해부", title_jp: "乙女解剖", title_hi: "おとめかいぼう", title_hangul: "오토메카이보", length: 111 },
    { id: 93, name: "푸르게 달려라!", title_jp: "青く駆けろ！", title_hi: "あおくかけろ！", title_hangul: "아오쿠카케로！", length: 117 },
    { id: 94, name: "너무 아파 아프고 싶어", title_jp: "とても痛い痛がりたい", title_hi: "とてもいたいいたがりたい", title_hangul: "도테모이타이타가리타이", length: 113 },
    { id: 95, name: "위풍당당", title_jp: "威風堂々", title_hi: "いふうどうどう", title_hangul: "이후도도", length: 145 },
    { id: 96, name: "from Y to Y", title_jp: "from Y to Y", title_hi: "from Y to Y", title_hangul: "프롬 와이 투 와이", length: 156 },
    { id: 97, name: "날이 개길 기다려", title_jp: "霽れを待つ", title_hi: "さいれをまつ", title_hangul: "사이레오마쓰", length: 114 },
    { id: 98, name: "로스트 원의 호곡", title_jp: "ロストワンの号哭", title_hi: "ろすとわんのごうこく", title_hangul: "로스토완노고코쿠", length: 108 },
    { id: 99, name: "모어! 점프! 모어!", title_jp: "モア！ジャンプ！モア！", title_hi: "もあ！じゃんぷ！もあ！", title_hangul: "모아！잔푸！모아！", length: 124 },
    { id: 100, name: "ECHO", title_jp: "ECHO", title_hi: "ECHO", title_hangul: "에코", length: 99 },
    { id: 101, name: "RAD DOGS", title_jp: "RAD DOGS", title_hi: "RAD DOGS", title_hangul: "라드 독스", length: 140 },
    { id: 102, name: "유령 도쿄", title_jp: "幽霊東京", title_hi: "ゆうれいとうきょう", title_hangul: "유레이토쿄", length: 133 },
    { id: 103, name: "무지갯빛 스토리즈", title_jp: "ニジイロストーリーズ", title_hi: "にじいろすとーりーず", title_hangul: "니지로스토리즈", length: 122 },
    { id: 104, name: "샹드리용 10th Anniversary", title_jp: "サンドリヨン 10th Anniversary", title_hi: "さんどりよん 10th Anniversary", title_hangul: "샹드리용 10주년", length: 118 },
    { id: 105, name: "원스 어폰 어 드림", title_jp: "ワンスアポンアドリーム", title_hi: "わんすあぽんあどりーむ", title_hangul: "완스아폰아도리무", length: 113 },
    { id: 106, name: "마음에 드시는 대로", title_jp: "お気に召すまま", title_hi: "おきにめすまま", title_hangul: "오키니메스마마", length: 113 },
    { id: 107, name: "밀크 크라운 온 소네치카", title_jp: "ミルククラウン・オン・ソーネチカ", title_hi: "みるくくらうん・おん・そーねちか", title_hangul: "미루쿠쿠라운・온・소네치카", length: 135 },
    { id: 108, name: "사랑받지 못해도 네가 있어", title_jp: "愛されなくても君がいる", title_hi: "あいされなくてもくんがいる", title_hangul: "아이사레나쿠테모쿤가이루", length: 140 },
    { id: 109, name: "울려퍼져라", title_jp: "ヒビカセ", title_hi: "ひびかせ", title_hangul: "히비카세", length: 115 },
    { id: 110, name: "천본앵", title_jp: "千本桜", title_hi: "せんぼんざくら", title_hangul: "센본자쿠라", length: 124 },
    { id: 111, name: "커틀러리", title_jp: "カトラリー", title_hi: "かとらりー", title_hangul: "가토라리", length: 111 },
    { id: 112, name: "천사의 클로버", title_jp: "天使のクローバー", title_hi: "てんしのくろーばー", title_hangul: "덴시노쿠로바", length: 118 },
    { id: 113, name: "롤링 걸", title_jp: "ローリンガール", title_hi: "ろーりんがーる", title_hangul: "로린가루", length: 121 },
    { id: 114, name: "겉과 속의 러버즈", title_jp: "裏表ラバーズ", title_hi: "うらおもてらばーず", title_hangul: "우라오모테라바즈", length: 111 },
    { id: 115, name: "언노운 마더 구스", title_jp: "アンノウン・マザーグース", title_hi: "あんのうん・まざーぐーす", title_hangul: "안논・마자구스", length: 137 },
    { id: 116, name: "아이디 스마일", title_jp: "アイディスマイル", title_hi: "あいでぃすまいる", title_hangul: "아이데이스마이루", length: 135 },
    { id: 117, name: "ODDS＆ENDS", title_jp: "ODDS＆ENDS", title_hi: "ODDS＆ENDS", title_hangul: "오즈 & 엔즈", length: 94 },
    { id: 118, name: "*헬로, 플래닛.", title_jp: "＊ハロー、プラネット。", title_hi: "＊はろー、ぷらねっと。", title_hangul: "＊하로、푸라넷토。", length: 118 },
    { id: 119, name: "월즈 엔드 댄스홀", title_jp: "ワールズエンド・ダンスホール", title_hi: "わーるずえんど・だんすほーる", title_hangul: "와루즈엔도・단스호루", length: 103 },
    { id: 120, name: "가지마", title_jp: "いかないで", title_hi: "いかないで", title_hangul: "이카나이데", length: 116 },
    { id: 121, name: "로미오와 신데렐라", title_jp: "ロミオとシンデレラ", title_hi: "ろみおとしんでれら", title_hangul: "로미오토신데레라", length: 115 },
    { id: 122, name: "포지티브☆댄스 타임", title_jp: "ポジティブ☆ダンスタイム", title_hi: "ぽじてぃぶ☆だんすたいむ", title_hangul: "포지테이부☆단스타이무", length: 116 },
    { id: 123, name: "드리밍 츄츄", title_jp: "どりーみんチュチュ", title_hi: "どりーみんちゅちゅ", title_hangul: "도리민추추", length: 140 },
    { id: 124, name: "미쿠미쿠하게 해줄게♪", title_jp: "みくみくにしてあげる♪【してやんよ】", title_hi: "みくみくにしてあげる♪【してやんよ】", title_hangul: "미쿠미쿠니시테아게루♪【시테얀요】", length: 101 },
    { id: 125, name: "보카 델라 베리타", title_jp: "ボッカデラベリタ", title_hi: "ぼっかでらべりた", title_hangul: "봇카데라베리타", length: 117 },
    { id: 126, name: "시네마", title_jp: "シネマ", title_hi: "しねま", title_hangul: "시네마", length: 107 },
    { id: 127, name: "톤데모 원더즈", title_jp: "トンデモワンダーズ", title_hi: "とんでもわんだーず", title_hangul: "돈데모완다즈", length: 124 },
    { id: 128, name: "Brand New Day", title_jp: "Brand New Day", title_hi: "Brand New Day", title_hangul: "브랜드 뉴 데이", length: 131 },
    { id: 129, name: "비터 초코 데코레이션", title_jp: "ビターチョコデコレーション", title_hi: "びたーちょこでこれーしょん", title_hangul: "비타초코데코레숀", length: 129 },
    { id: 130, name: "프롬 도쿄", title_jp: "フロムトーキョー", title_hi: "ふろむとーきょー", title_hangul: "후로무토쿄", length: 100 },
    { id: 131, name: "하츠네 미쿠의 격창", title_jp: "初音ミクの激唱", title_hi: "はつねみくのげきしょう", title_hangul: "하쓰네미쿠노게키쇼", length: 161 },
    { id: 132, name: "「１」", title_jp: "「１」", title_hi: "「１」", title_hangul: "「１」", length: 98 },
    { id: 133, name: "악마가 춤추는 법", title_jp: "悪魔の踊り方", title_hi: "あくまのおどりほう", title_hangul: "아쿠마노도리호", length: 118 },
    { id: 134, name: "텔레캐스터 비보이", title_jp: "テレキャスタービーボーイ", title_hi: "てれきゃすたーびーぼーい", title_hangul: "데레캬스타비보이", length: 98 },
    { id: 135, name: "육조 년과 하룻밤 이야기", title_jp: "六兆年と一夜物語", title_hi: "ろくちょうねんといちやものがたり", title_hangul: "로쿠초넨토이치야모노가타리", length: 124 },
    { id: 136, name: "칠드런 레코드", title_jp: "チルドレンレコード", title_hi: "ちるどれんれこーど", title_hangul: "지루도렌레코도", length: 128 },
    { id: 137, name: "꽃을 노래하다", title_jp: "花を唄う", title_hi: "はなをうたう", title_hangul: "하나오타우", length: 111 },
    { id: 138, name: "KING", title_jp: "KING", title_hi: "KING", title_hangul: "킹", length: 135 },
    { id: 139, name: "밤을 달리다", title_jp: "夜に駆ける", title_hi: "よるにかける", title_hangul: "요루니카케루", length: 139 },
    { id: 140, name: "아이스 드롭", title_jp: "アイスドロップ", title_hi: "あいすどろっぷ", title_hangul: "아이스도롯푸", length: 106 },
    { id: 141, name: "군청찬가", title_jp: "群青讃歌", title_hi: "ぐんじょうさんか", title_hangul: "군조산카", length: 99 },
    { id: 142, name: "재생", title_jp: "再生", title_hi: "さいせい", title_hangul: "사이세이", length: 103 },
    { id: 143, name: "트래픽 잼", title_jp: "トラフィック・ジャム", title_hi: "とらふぃっく・じゃむ", title_hangul: "도라후잇쿠・자무", length: 130 },
    { id: 144, name: "사랑의 마테리얼", title_jp: "アイノマテリアル", title_hi: "あいのまてりある", title_hangul: "아이노마테리아루", length: 124 },
    { id: 145, name: "베놈", title_jp: "ベノム", title_hi: "べのむ", title_hangul: "베노무", length: 129 },
    { id: 146, name: "리모컨", title_jp: "リモコン", title_hi: "りもこん", title_hangul: "리모콘", length: 133 },
    { id: 147, name: "꼭두각시 피에로", title_jp: "からくりピエロ", title_hi: "からくりぴえろ", title_hangul: "가라쿠리피에로", length: 138 },
    { id: 148, name: "ray", title_jp: "ray", title_hi: "ray", title_hangul: "레이", length: 131 },
    { id: 149, name: "카나데토모스소라", title_jp: "カナデトモスソラ", title_hi: "かなでともすそら", title_hangul: "가나데토모스소라", length: 115 },
    { id: 150, name: "토키오 펑카", title_jp: "トキヲ・ファンカ", title_hi: "ときを・ふぁんか", title_hangul: "도키오・후안카", length: 108 },
    { id: 151, name: "거품 미래", title_jp: "泡沫未来", title_hi: "ほうまつみらい", title_hangul: "호마쓰미라이", length: 104 },
    { id: 152, name: "누군가의 심장이 될 수 있다면", title_jp: "だれかの心臓になれたなら", title_hi: "だれかのしんぞうになれたなら", title_hangul: "다레카노신조니나레타나라", length: 117 },
    { id: 153, name: "Miku", title_jp: "Miku", title_hi: "Miku", title_hangul: "미쿠", length: 156 },
    { id: 154, name: "지구 최후의 고백을", title_jp: "地球最後の告白を", title_hi: "ちきゅうさいごのこくはくを", title_hangul: "지큐사이고노코쿠하쿠오", length: 128 },
    { id: 155, name: "심박수♯0822", title_jp: "心拍数♯0822", title_hi: "しんぱくすう♯0822", title_hangul: "신파쿠스♯0822", length: 123 },
    { id: 156, name: "Beat Eater", title_jp: "Beat Eater", title_hi: "Beat Eater", title_hangul: "비트 이터", length: 100 },
    { id: 157, name: "마슈마리", title_jp: "マシュマリー", title_hi: "ましゅまりー", title_hangul: "마슈마리", length: 133 },
    { id: 158, name: "난센스 문학", title_jp: "ナンセンス文学", title_hi: "なんせんすぶんがく", title_hangul: "난센스분가쿠", length: 132 },
    { id: 159, name: "STAGE OF SEKAI", title_jp: "STAGE OF SEKAI", title_hi: "STAGE OF SEKAI", title_hangul: "스테이지 오브 세카이", length: 122 },
    { id: 160, name: "쇼타임 룰러", title_jp: "ショウタイム・ルーラー", title_hi: "しょうたいむ・るーらー", title_hangul: "쇼타이무・루라", length: 109 },
    { id: 161, name: "magic number", title_jp: "magic number", title_hi: "magic number", title_hangul: "매직 넘버", length: 111 },
    { id: 162, name: "엔드마크에 희망과 눈물을 더하며", title_jp: "エンドマークに希望と涙を添えて", title_hi: "えんどまーくにきぼうとなみだをそえて", title_hangul: "엔도마쿠니키보토나미다오소에테", length: 142 },
    { id: 163, name: "the EmpErroR", title_jp: "the EmpErroR", title_hi: "the EmpErroR", title_hangul: "디 엠페러", length: 127 },
    { id: 164, name: "Don't Fight The Music", title_jp: "Don't Fight The Music", title_hi: "Don't Fight The Music", title_hangul: "돈 파이트 더 뮤직", length: 160 },
    { id: 165, name: "그랬지!!", title_jp: "そうだった！！", title_hi: "そうだった！！", title_hangul: "소닷타！！", length: 127 },
    { id: 166, name: "Glory Steady Go!", title_jp: "Glory Steady Go!", title_hi: "Glory Steady Go!", title_hangul: "글로디 스테디 고!", length: 99 },
    { id: 167, name: "얼터 에고", title_jp: "オルターエゴ", title_hi: "おるたーえご", title_hangul: "오루타에고", length: 152 },
    { id: 168, name: "달링 댄스", title_jp: "ダーリンダンス", title_hi: "だーりんだんす", title_hangul: "다린단스", length: 103 },
    { id: 169, name: "소녀 레이", title_jp: "少女レイ", title_hi: "しょうじょれい", title_hangul: "쇼조레이", length: 160 },
    { id: 170, name: "빌런", title_jp: "ヴィラン", title_hi: "ゔぃらん", title_hangul: "ヴ이란", length: 150 },
    { id: 171, name: "아지랑이 데이즈", title_jp: "カゲロウデイズ", title_hi: "かげろうでいず", title_hangul: "가게로데이즈", length: 144 },
    { id: 172, name: "Happy Halloween", title_jp: "Happy Halloween", title_hi: "Happy Halloween", title_hangul: "해피 할로윈", length: 124 },
    { id: 173, name: "유성의 펄스", title_jp: "流星のパルス", title_hi: "りゅうせいのぱるす", title_hangul: "류세이노파루스", length: 122 },
    { id: 174, name: "이얼 판클럽", title_jp: "いーあるふぁんくらぶ", title_hi: "いーあるふぁんくらぶ", title_hangul: "이아루후안쿠라부", length: 126 },
    { id: 175, name: "친애하는 도플갱어에게", title_jp: "拝啓ドッペルゲンガー", title_hi: "はいけいどっぺるげんがー", title_hangul: "하이케이돗페루겐가", length: 155 },
    { id: 176, name: "머신건 포엠 돌", title_jp: "マシンガンポエムドール", title_hi: "ましんがんぽえむどーる", title_hangul: "마신간포에무도루", length: 141 },
    { id: 177, name: "오른 어깨의 나비", title_jp: "右肩の蝶", title_hi: "みぎかたのちょう", title_hangul: "미기카타노초", length: 133 },
    { id: 178, name: "빙그레^^조사대의 테마", title_jp: "にっこり^^調査隊のテーマ", title_hi: "にっこり^^ちょうさたいのてーま", title_hangul: "닛코리^^초사타이노테마", length: 126 },
    { id: 179, name: "노심융해", title_jp: "炉心融解", title_hi: "ろしんゆうかい", title_hangul: "로신유카이", length: 124 },
    { id: 180, name: "미라이", title_jp: "ミライ", title_hi: "みらい", title_hangul: "미라이", length: 159 },
    { id: 181, name: "사랑해줘 사랑해줘 사랑해줘", title_jp: "愛して愛して愛して", title_hi: "いとしていとしていとして", title_hangul: "이토시테이토시테이토시테", length: 130 },
    { id: 182, name: "Flyer!", title_jp: "Flyer!", title_hi: "Flyer!", title_hangul: "플라이어!", length: 123 },
    { id: 183, name: "픽서", title_jp: "フィクサー", title_hi: "ふぃくさー", title_hangul: "후이쿠사", length: 123 },
    { id: 184, name: "Hello,world!", title_jp: "Hello,world!", title_hi: "Hello,world!", title_hangul: "헬로, 월드!", length: 101 },
    { id: 185, name: "식 오브 하우스!", title_jp: "しっくおぶはうす！", title_hi: "しっくおぶはうす！", title_hangul: "싯쿠오부하우스！", length: 142 },
    { id: 186, name: "하츠네 천지개벽 신화", title_jp: "初音天地開闢神話", title_hi: "はつねてんちかいびゃくしんわ", title_hangul: "하쓰네텐치카이뱌쿠신와", length: 182 },
    { id: 187, name: "로워", title_jp: "ロウワー", title_hi: "ろうわー", title_hangul: "로와", length: 108 },
    { id: 188, name: "마음 예보", title_jp: "心予報", title_hi: "こころよほう", title_hangul: "고코로요호", length: 134 },
    { id: 189, name: "노마드", title_jp: "ノマド", title_hi: "のまど", title_hangul: "노마도", length: 92 },
    { id: 190, name: "악의 딸", title_jp: "悪ノ娘", title_hi: "あくのむすめ", title_hangul: "아쿠노무스메", length: 92 },
    { id: 191, name: "악의 하인", title_jp: "悪ノ召使", title_hi: "あくのめしつかい", title_hangul: "아쿠노메시쓰카이", length: 94 },
    { id: 192, name: "떠나는 사람들의 왈츠", title_jp: "去り人達のワルツ", title_hi: "さりひとたちのわるつ", title_hangul: "사리히토타치노와루쓰", length: 100 },
    { id: 193, name: "월드와이드 원더", title_jp: "ワールドワイドワンダー", title_hi: "わーるどわいどわんだー", title_hangul: "와루도와이도완다", length: 97 },
    { id: 194, name: "망상감상대상연맹", title_jp: "妄想感傷代償連盟", title_hi: "もうそうかんしょうだいしょうれんめい", title_hangul: "모소칸쇼다이쇼렌메이", length: 141 },
    { id: 195, name: "PaⅢ.SENSATION", title_jp: "PaⅢ.SENSATION", title_hi: "PaⅢ.SENSATION", title_hangul: "PaⅢ.센세이션", length: 134 },
    { id: 196, name: "오더메이드", title_jp: "オーダーメイド", title_hi: "おーだーめいど", title_hangul: "오다메이도", length: 125 },
    { id: 197, name: "라스트 스코어", title_jp: "ラストスコア", title_hi: "らすとすこあ", title_hangul: "라스토스코아", length: 143 },
    { id: 198, name: "굿바이 선언", title_jp: "グッバイ宣言", title_hi: "ぐっばいせんげん", title_hangul: "굿바이센겐", length: 126 },
    { id: 199, name: "고스트 룰", title_jp: "ゴーストルール", title_hi: "ごーすとるーる", title_hangul: "고스토루루", length: 142 },
    { id: 200, name: "갈란드", title_jp: "ガランド", title_hi: "がらんど", title_hangul: "가란도", length: 131 },
    { id: 201, name: "신의 뜻대로", title_jp: "神のまにまに", title_hi: "かみのまにまに", title_hangul: "가미노마니마니", length: 133 },
    { id: 202, name: "Q", title_jp: "Q", title_hi: "Q", title_hangul: "Q", length: 131 },
    { id: 203, name: "트리콜로주", title_jp: "トリコロージュ", title_hi: "とりころーじゅ", title_hangul: "도리코로주", length: 125 },
    { id: 204, name: "웃세와", title_jp: "うっせぇわ", title_hi: "うっせぇわ", title_hangul: "웃세와", length: 136 },
    { id: 205, name: "오도", title_jp: "踊", title_hi: "よう", title_hangul: "요", length: 141 },
    { id: 206, name: "너의 색깔 마린 스노우", title_jp: "君色マリンスノウ", title_hi: "くんいろまりんすのう", title_hangul: "군이로마린스노", length: 152 },
    { id: 207, name: "Peaky Peaky", title_jp: "Peaky Peaky", title_hi: "Peaky Peaky", title_hangul: "피키 피키", length: 106 },
    { id: 208, name: "우리는 아직 언더그라운드", title_jp: "僕らまだアンダーグラウンド", title_hi: "ぼくらまだあんだーぐらうんど", title_hangul: "보쿠라마단다구라운도", length: 122 },
    { id: 209, name: "메타모 리본", title_jp: "メタモリボン", title_hi: "めたもりぼん", title_hangul: "메타모리본", length: 104 },
    { id: 210, name: "비와 페트라", title_jp: "雨とペトラ", title_hi: "あめとぺとら", title_hangul: "아메토페토라", length: 125 },
    { id: 211, name: "이프", title_jp: "イフ", title_hi: "いふ", title_hangul: "이후", length: 130 },
    { id: 212, name: "별하늘의 멜로디", title_jp: "星空のメロディー", title_hi: "ほしぞらのめろでぃー", title_hangul: "호시조라노메로데이", length: 108 },
    { id: 213, name: "뱀파이어", title_jp: "ヴァンパイア", title_hi: "ゔぁんぱいあ", title_hangul: "ヴ안파이아", length: 142 },
    { id: 214, name: "팔레트에는 네가 가득", title_jp: "パレットには君がいっぱい", title_hi: "ぱれっとにはくんがいっぱい", title_hangul: "파렛토니하쿤가잇파이", length: 134 },
    { id: 215, name: "쥬다스", title_jp: "ジウダス", title_hi: "じうだす", title_hangul: "지우다스", length: 103 },
    { id: 216, name: "루카루카★나이트 피버", title_jp: "ルカルカ★ナイトフィーバー", title_hi: "るかるか★ないとふぃーばー", title_hangul: "루카루카★나이토후이바", length: 139 },
    { id: 217, name: "거리", title_jp: "街", title_hi: "まち", title_hangul: "마치", length: 103 },
    { id: 218, name: "메류", title_jp: "メリュー", title_hi: "めりゅー", title_hangul: "메류", length: 140 },
    { id: 219, name: "모래의 행성", title_jp: "砂の惑星", title_hi: "すなのわくせい", title_hangul: "스나노와쿠세이", length: 134 },
    { id: 220, name: "도넛홀 2024", title_jp: "ドーナツホール 2024", title_hi: "どーなつほーる 2024", title_hangul: "도나쓰호루 2024", length: 138 },
    { id: 221, name: "마트료시카", title_jp: "マトリョシカ", title_hi: "まとりょしか", title_hangul: "마토료시카", length: 106 },
    { id: 222, name: "피아노×포르테×스캔들", title_jp: "ピアノ×フォルテ×スキャンダル", title_hi: "ぴあの×ふぉるて×すきゃんだる", title_hangul: "피아노×후오루테×스캰다루", length: 132 },
    { id: 223, name: "천년의 독주가", title_jp: "千年の独奏歌", title_hi: "せんねんのどくそううた", title_hangul: "센넨노도쿠소타", length: 152 },
    { id: 224, name: "88☆彡", title_jp: "88☆彡", title_hi: "88☆さん", title_hangul: "88☆산", length: 127 },
    { id: 225, name: "에고 록", title_jp: "エゴロック", title_hi: "えごろっく", title_hangul: "에고롯쿠", length: 112 },
    { id: 226, name: "로스트 앤 파운드", title_jp: "ロストエンファウンド", title_hi: "ろすとえんふぁうんど", title_hangul: "로스토엔후아운도", length: 156 },
    { id: 227, name: "ONESELF", title_jp: "ONESELF", title_hi: "ONESELF", title_hangul: "원셀프", length: 129 },
    { id: 228, name: "Goodbye", title_jp: "Goodbye", title_hi: "Goodbye", title_hangul: "굿바이", length: 128 },
    { id: 229, name: "뇌장작렬 걸", title_jp: "脳漿炸裂ガール", title_hi: "のうしょうさくれつがーる", title_hangul: "노쇼사쿠레쓰가루", length: 144 },
    { id: 230, name: "샐러맨더", title_jp: "サラマンダー", title_hi: "さらまんだー", title_hangul: "사라만다", length: 158 },
    { id: 231, name: "아이덴티티", title_jp: "アイデンティティ", title_hi: "あいでんてぃてぃ", title_hangul: "아이덴테이테이", length: 157 },
    { id: 232, name: "푸른색 물감", title_jp: "青色絵具", title_hi: "あおいろえのぐ", title_hangul: "아오이로에노구", length: 156 },
    { id: 233, name: "코스모 스파이스", title_jp: "コスモスパイス", title_hi: "こすもすぱいす", title_hangul: "고스모스파이스", length: 130 },
    { id: 234, name: "도쿠가와 컵누들 금지령", title_jp: "徳川カップヌードル禁止令", title_hi: "とくがわかっぷぬーどるきんしれい", title_hangul: "도쿠가와캇푸누도루킨시레이", length: 128 },
    { id: 235, name: "Journey", title_jp: "Journey", title_hi: "Journey", title_hangul: "저니", length: 166 },
    { id: 236, name: "Voices", title_jp: "Voices", title_hi: "Voices", title_hangul: "보이시즈", length: 125 },
    { id: 237, name: "너의 밤을 줘", title_jp: "君の夜をくれ", title_hi: "くんのよるをくれ", title_hangul: "군노요루오쿠레", length: 122 },
    { id: 238, name: "블랙★록 슈터", title_jp: "ブラック★ロックシューター", title_hi: "ぶらっく★ろっくしゅーたー", title_hangul: "부랏쿠★롯쿠슈타", length: 115 },
    { id: 239, name: "월광", title_jp: "月光", title_hi: "げっこう", title_hangul: "겟코", length: 157 },
    { id: 240, name: "춤춰라 오케스트라", title_jp: "踊れオーケストラ", title_hi: "おどれおーけすとら", title_hangul: "오도레오케스토라", length: 110 },
    { id: 242, name: "토리노코시티", title_jp: "トリノコシティ", title_hi: "とりのこしてぃ", title_hangul: "도리노코시테이", length: 117 },
    { id: 243, name: "Calc.", title_jp: "Calc.", title_hi: "Calc.", title_hangul: "칼크.", length: 145 },
    { id: 244, name: "Awake Now", title_jp: "Awake Now", title_hi: "Awake Now", title_hangul: "어웨이크 나우", length: 122 },
    { id: 245, name: "아훔의 비트", title_jp: "阿吽のビーツ", title_hi: "あうんのびーつ", title_hangul: "아운노비쓰", length: 136 },
    { id: 246, name: "에일리언 에일리언", title_jp: "エイリアンエイリアン", title_hi: "えいりあんえいりあん", title_hangul: "에이리안에이리안", length: 144 },
    { id: 247, name: "Copycat", title_jp: "Copycat", title_hi: "Copycat", title_hangul: "카피캣", length: 126 },
    { id: 248, name: "버그", title_jp: "バグ", title_hi: "ばぐ", title_hangul: "바구", length: 128 },
    { id: 249, name: "우리들의 16bit 전쟁", title_jp: "ぼくらの16bit戦争", title_hi: "ぼくらの16bitせんそう", title_hangul: "보쿠라노16bit센소", length: 148 },
    { id: 250, name: "썩은 외도와 초콜릿", title_jp: "腐れ外道とチョコレゐト", title_hi: "くされがいどうとちょこれゐと", title_hangul: "구사레가이도토초코레ヰ토", length: 132 },
    { id: 251, name: "프로일라인=비블리오테카", title_jp: "フロイライン＝ビブリォチカ", title_hi: "ふろいらいん＝びぶりぉちか", title_hangul: "후로이라인＝비부리오치카", length: 146 },
    { id: 252, name: "DREAM PLACE", title_jp: "DREAM PLACE", title_hi: "DREAM PLACE", title_hangul: "드림 플레이스", length: 142 },
    { id: 253, name: "DAYBREAK FRONTLINE", title_jp: "DAYBREAK FRONTLINE", title_hi: "DAYBREAK FRONTLINE", title_hangul: "데이브레이크 프론트라인", length: 139 },
    { id: 254, name: "미완성 찬가", title_jp: "未完成讃歌", title_hi: "みかんせいさんか", title_hangul: "미칸세이산카", length: 156 },
    { id: 255, name: "밤새도록 널 생각해", title_jp: "夜もすがら君想ふ", title_hi: "よるもすがらくんおもふ", title_hangul: "요루모스가라쿤오모후", length: 146 },
    { id: 256, name: "더블 래리어트", title_jp: "ダブルラリアット", title_hi: "だぶるらりあっと", title_hangul: "다부루라리앗토", length: 142 },
    { id: 257, name: "번질번질", title_jp: "てらてら", title_hi: "てらてら", title_hangul: "데라테라", length: 136 },
    { id: 258, name: "심해소녀", title_jp: "深海少女", title_hi: "しんかいしょうじょ", title_hangul: "신카이쇼조", length: 145 },
    { id: 259, name: "the WALL", title_jp: "the WALL", title_hi: "the WALL", title_hangul: "더 월", length: 112 },
    { id: 260, name: "라브카?", title_jp: "ラブカ？", title_hi: "らぶか？", title_hangul: "라부카？", length: 104 },
    { id: 261, name: "별가루 유토피아", title_jp: "星屑ユートピア", title_hi: "ほしくずゆーとぴあ", title_hangul: "호시쿠즈유토피아", length: 132 },
    { id: 262, name: "제국소녀", title_jp: "帝国少女", title_hi: "ていこくしょうじょ", title_hangul: "데이코쿠쇼조", length: 148 },
    { id: 263, name: "Highlight", title_jp: "Highlight", title_hi: "Highlight", title_hangul: "하이라이트", length: 97 },
    { id: 264, name: "파라솔 사이다", title_jp: "パラソルサイダー", title_hi: "ぱらそるさいだー", title_hangul: "파라소루사이다", length: 91 },
    { id: 265, name: "Change me", title_jp: "Change me", title_hi: "Change me", title_hangul: "체인지 미", length: 147 },
    { id: 266, name: "YY", title_jp: "YY", title_hi: "YY", title_hangul: "와이와이", length: 145 },
    { id: 267, name: "가사화", title_jp: "仮死化", title_hi: "かしか", title_hangul: "가시카", length: 132 },
    { id: 268, name: "논브레스 오블리주", title_jp: "ノンブレス・オブリージュ", title_hi: "のんぶれす・おぶりーじゅ", title_hangul: "논부레스・오부리주", length: 130 },
    { id: 269, name: "론리 유니버스", title_jp: "ロンリーユニバース", title_hi: "ろんりーゆにばーす", title_hangul: "론리유니바스", length: 141 },
    { id: 270, name: "진흙 속에 피다", title_jp: "泥中に咲く", title_hi: "でいちゅうにさく", title_hangul: "데이추니사쿠", length: 146 },
    { id: 271, name: "따뜻하다고", title_jp: "あったかいと", title_hi: "あったかいと", title_hangul: "앗타카이토", length: 149 },
    { id: 272, name: "게헨나", title_jp: "ジェヘナ", title_hi: "じぇへな", title_hangul: "지에헤나", length: 154 },
    { id: 273, name: "퓨처 이브", title_jp: "フューチャー・イヴ", title_hi: "ふゅーちゃー・いゔ", title_hangul: "후우차・이ヴ", length: 153 },
    { id: 274, name: "그래도 괜찮아", title_jp: "それでもいいんだよ", title_hi: "それでもいいんだよ", title_hangul: "소레데모인다요", length: 128 },
    { id: 275, name: "파라디클로로벤젠", title_jp: "パラジクロロベンゼン", title_hi: "ぱらじくろろべんぜん", title_hangul: "파라지쿠로로벤젠", length: 149 },
    { id: 276, name: "샨티", title_jp: "シャンティ", title_hi: "しゃんてぃ", title_hangul: "샨테이", length: 131 },
    { id: 277, name: "포니", title_jp: "フォニイ", title_hi: "ふぉにい", title_hangul: "후오니", length: 144 },
    { id: 278, name: "Bad ∞ End ∞ Night", title_jp: "Bad ∞ End ∞ Night", title_hi: "Bad ∞ End ∞ Night", title_hangul: "배드 ∞ 엔드 ∞ 나이트", length: 118 },
    { id: 279, name: "여기는, 행복안심위원회입니다.", title_jp: "こちら、幸福安心委員会です。", title_hi: "こちら、こうふくあんしんいいんかいです。", title_hangul: "고치라、코후쿠안신인카이데스。", length: 146 },
    { id: 280, name: "공허함을 부추기다", title_jp: "虚ろを扇ぐ", title_hi: "うつろをおうぎぐ", title_hangul: "우쓰로기구", length: 157 },
    { id: 281, name: "변덕쟁이 메르시", title_jp: "気まぐれメルシィ", title_hi: "きまぐれめるしぃ", title_hangul: "기마구레메루시", length: 149 },
    { id: 282, name: "별하늘 오케스트라", title_jp: "星空オーケストラ", title_hi: "ほしぞらおーけすとら", title_hangul: "호시조라오케스토라", length: 125 },
    { id: 283, name: "레이니 스노우드롭", title_jp: "レイニースノードロップ", title_hi: "れいにーすのーどろっぷ", title_hangul: "레이니스노도롯푸", length: 151 },
    { id: 284, name: "인비저블", title_jp: "インビジブル", title_hi: "いんびじぶる", title_hangul: "인비지부루", length: 144 },
    { id: 285, name: "ÅMARA(대미래전뇌)", title_jp: "ÅMARA(大未来電脳)", title_hi: "ÅMARA(だいみらいでんのう)", title_hangul: "아마라(다이미라이덴노오)", length: 155 },
    { id: 286, name: "Hello, Worker", title_jp: "Hello, Worker", title_hi: "Hello, Worker", title_hangul: "헬로, 워커", length: 103 },
    { id: 287, name: "나는, 우리는", title_jp: "私は、私達は", title_hi: "わたしは、わたしたちは", title_hangul: "와타시하、와타시타치하", length: 108 },
    { id: 288, name: "언해피 리프레인", title_jp: "アンハッピーリフレイン", title_hi: "あんはっぴーりふれいん", title_hangul: "안핫피리후레인", length: 133 },
    { id: 289, name: "천성의 약함", title_jp: "天ノ弱", title_hi: "てんのじゃく", title_hangul: "덴노자쿠", length: 109 },
    { id: 291, name: "펠레스", title_jp: "フェレス", title_hi: "ふぇれす", title_hangul: "후에레스", length: 140 },
    { id: 292, name: "하나 둘 하고 셋에", title_jp: "いちにのさんで", title_hi: "いちにのさんで", title_hangul: "이치니노산데", length: 162 },
    { id: 293, name: "아이러니", title_jp: "アイロニ", title_hi: "あいろに", title_hangul: "아이로니", length: 144 },
    { id: 294, name: "그것이 당신의 행복이라 할지라도", title_jp: "それがあなたの幸せとしても", title_hi: "それがあなたのしあわせとしても", title_hangul: "소레가나타노시아와세토시테모", length: 128 },
    { id: 295, name: "플로트 플래너", title_jp: "フロート・プランナー", title_hi: "ふろーと・ぷらんなー", title_hangul: "후로토・푸란나", length: 104 },
    { id: 296, name: "칸타렐라", title_jp: "カンタレラ", title_hi: "かんたれら", title_hangul: "간타레라", length: 126 },
    { id: 297, name: "p.h.", title_jp: "p.h.", title_hi: "p.h.", title_hangul: "ph", length: 111 },
    { id: 298, name: "온라인 게임 폐인 슈프레히코어", title_jp: "ネトゲ廃人シュプレヒコール", title_hi: "ねとげはいじんしゅぷれひこーる", title_hangul: "네토게하이진슈푸레히코루", length: 149 },
    { id: 299, name: "에고이스트", title_jp: "エゴイスト", title_hi: "えごいすと", title_hangul: "에고이스토", length: 147 },
    { id: 300, name: "잠자", title_jp: "ザムザ", title_hi: "ざむざ", title_hangul: "자무자", length: 115 },
    { id: 301, name: "나의 사랑은 헬파이어", title_jp: "私の恋はヘルファイア", title_hi: "わたしのこいはへるふぁいあ", title_hangul: "와타시노코이하헤루후아이아", length: 150 },
    { id: 302, name: "후레이", title_jp: "フレー", title_hi: "ふれー", title_hangul: "후레", length: 139 },
    { id: 303, name: "린짱 나우!", title_jp: "リンちゃんなう！", title_hi: "りんちゃんなう！", title_hangul: "린찬나우！", length: 149 },
    { id: 304, name: "I랍니다", title_jp: "Iなんです", title_hi: "Iなんです", title_hangul: "아이난데스", length: 106 },
    { id: 305, name: "스트로보 라스트", title_jp: "ストロボラスト", title_hi: "すとろぼらすと", title_hangul: "스토로보라스토", length: 132 },
    { id: 306, name: "1925", title_jp: "1925", title_hi: "1925", title_hangul: "1925", length: 142 },
    { id: 307, name: "어린이 전쟁", title_jp: "おこちゃま戦争", title_hi: "おこちゃませんそう", title_hangul: "오코차마센소", length: 146 },
    { id: 308, name: "복숭아색 열쇠", title_jp: "ももいろの鍵", title_hi: "ももいろのかぎ", title_hangul: "모모이로노카기", length: 132 },
    { id: 309, name: "Afterglow", title_jp: "Afterglow", title_hi: "Afterglow", title_hangul: "애프터글로우", length: 147 },
    { id: 310, name: "Flyway", title_jp: "Flyway", title_hi: "Flyway", title_hangul: "플라이웨이", length: 129 },
    { id: 311, name: "새벽과 반딧불이", title_jp: "夜明けと蛍", title_hi: "よあけとほたる", title_hangul: "요아케토호타루", length: 146 },
    { id: 312, name: "마음", title_jp: "ココロ", title_hi: "こころ", title_hangul: "고코로", length: 142 },
    { id: 313, name: "FREELY TOMORROW", title_jp: "FREELY TOMORROW", title_hi: "FREELY TOMORROW", title_hangul: "프릴리 투모로우", length: 138 },
    { id: 314, name: "양지의 찰나", title_jp: "陽だまりのセツナ", title_hi: "ようだまりのせつな", title_hangul: "요다마리노세쓰나", length: 116 },
    { id: 315, name: "What's up? Pop!", title_jp: "What's up? Pop!", title_hi: "What's up? Pop!", title_hangul: "왓츠 업 팝", length: 161 },
    { id: 316, name: "양이 한 마리", title_jp: "ひつじがいっぴき", title_hi: "ひつじがいっぴき", title_hangul: "히쓰지가잇피키", length: 129 },
    { id: 317, name: "마법 같은 뮤직!", title_jp: "魔法みたいなミュージック！", title_hi: "まほうみたいなみゅーじっく！", title_hangul: "마호미타이나뮤짓쿠！", length: 141 },
    { id: 318, name: "Sharing The World", title_jp: "Sharing The World", title_hi: "Sharing The World", title_hangul: "쉐어링 더 월드", length: 151 },
    { id: 319, name: "Decade", title_jp: "Decade", title_hi: "Decade", title_hangul: "디케이드", length: 145 },
    { id: 320, name: "Booo!", title_jp: "Booo!", title_hi: "Booo!", title_hangul: "부우!", length: 98 },
    { id: 321, name: "어트랙트 라이트", title_jp: "アトラクトライト", title_hi: "あとらくとらいと", title_hangul: "아토라쿠토라이토", length: 145 },
    { id: 322, name: "끊임없는 남빛", title_jp: "絶え間なく藍色", title_hi: "たえまなくあいいろ", title_hangul: "다에마나쿠아이로", length: 143 },
    { id: 323, name: "쾌청", title_jp: "快晴", title_hi: "かいせい", title_hangul: "가이세이", length: 151 },
    { id: 324, name: "모형 정원의 코랄", title_jp: "箱庭のコラル", title_hi: "はこにわのこらる", title_hangul: "하코니와노코라루", length: 130 },
    { id: 325, name: "돼지가 되어 yeah yeah", title_jp: "豚になってyeah yeah", title_hi: "ぶたになってyeah yeah", title_hangul: "부타니낫테yeah yeah", length: 121 },
    { id: 326, name: "천사의 날개.", title_jp: "天使の翼。", title_hi: "てんしのつばさ。", title_hangul: "덴시노쓰바사。", length: 169 },
    { id: 327, name: "SnowMix♪", title_jp: "SnowMix♪", title_hi: "SnowMix♪", title_hangul: "스노우믹스♪", length: 158 },
    { id: 328, name: "세카이 쨩과 카후 쨩의 장보기 합소곡", title_jp: "星界ちゃんと可不ちゃんのおつかい合騒曲", title_hi: "ほしかいちゃんとかふちゃんのおつかいごうそうきょく", title_hangul: "호시카이찬토카후찬노쓰카이고소쿄쿠", length: 154 },
    { id: 329, name: "야미나베!!!!", title_jp: "ヤミナベ!!!!", title_hi: "やみなべ!!!!", title_hangul: "야미나베!!!!", length: 130 },
    { id: 330, name: "인터뷰어", title_jp: "インタビュア", title_hi: "いんたびゅあ", title_hangul: "인타뷰아", length: 146 },
    { id: 331, name: "39", title_jp: "39", title_hi: "39", title_hangul: "39", length: 143 },
    { id: 332, name: "에필로그에 넌 없어", title_jp: "エピローグに君はいない", title_hi: "えぴろーぐにくんはいない", title_hangul: "에피로구니쿤하이나이", length: 113 },
    { id: 333, name: "Mr. Showtime", title_jp: "Mr. Showtime", title_hi: "Mr. Showtime", title_hangul: "미스터. 쇼타임", length: 139 },
    { id: 334, name: "Vampire's ∞ pathoS", title_jp: "Vampire's ∞ pathoS", title_hi: "Vampire's ∞ pathoS", title_hangul: "뱀파이어 ∞ 파토스", length: 124 },
    { id: 335, name: "트래시 앤드 트래시!", title_jp: "トラッシュ・アンド・トラッシュ！", title_hi: "とらっしゅ・あんど・とらっしゅ！", title_hangul: "도랏슈・안도・토랏슈！", length: 138 },
    { id: 336, name: "Be The MUSIC!", title_jp: "Be The MUSIC!", title_hi: "Be The MUSIC!", title_hangul: "비 더 뮤직!", length: 156 },
    { id: 337, name: "METEOR", title_jp: "METEOR", title_hi: "METEOR", title_hangul: "미티어", length: 140 },
    { id: 338, name: "Where shall we go?", title_jp: "Where shall we go?", title_hi: "Where shall we go?", title_hangul: "웨어 쉘 위 고?", length: 119 },
    { id: 339, name: "glow", title_jp: "glow", title_hi: "glow", title_hangul: "글로우", length: 159 },
    { id: 340, name: "정말 멋진 6월이었습니다", title_jp: "とても素敵な六月でした", title_hi: "とてもすてきなろくがつでした", title_hangul: "도테모스테키나로쿠가쓰데시타", length: 154 },
    { id: 341, name: "난청계 남자가 쓰러지지 않아", title_jp: "難聴系男子が倒せない", title_hi: "なんちょうけいだんしがたおせない", title_hangul: "난초케이단시가타오세나이", length: 142 },
    { id: 342, name: "Blue Star", title_jp: "Blue Star", title_hi: "Blue Star", title_hangul: "블루 스타", length: 147 },
    { id: 343, name: "스노우맨", title_jp: "スノーマン", title_hi: "すのーまん", title_hangul: "스노만", length: 144 },
    { id: 344, name: "뇌내혁명 걸", title_jp: "脳内革命ガール", title_hi: "のうないかくめいがーる", title_hangul: "노나이카쿠메이가루", length: 140 },
    { id: 345, name: "연극", title_jp: "演劇", title_hi: "えんげき", title_hangul: "엔게키", length: 126 },
    { id: 346, name: "아아, 훌륭한 고양이의 삶", title_jp: "嗚呼、素晴らしきニャン生", title_hi: "ああ、すばらしきにゃんなま", title_hangul: "아、스바라시키냔나마", length: 150 },
    { id: 347, name: "엔비자카의 재봉사", title_jp: "円尾坂の仕立屋", title_hi: "まるおさかのしたてや", title_hangul: "마루오사카노시타테야", length: 120 },
    { id: 348, name: "악덕의 저지먼트", title_jp: "悪徳のジャッジメント", title_hi: "あくとくのじゃっじめんと", title_hangul: "아쿠토쿠노잣지멘토", length: 128 },
    { id: 349, name: "악식녀 콘치타", title_jp: "悪食娘コンチータ", title_hi: "あくじきむすめこんちーた", title_hangul: "아쿠지키무스메콘치타", length: 102 },
    { id: 350, name: "잠재우는 공주로부터의 선물", title_jp: "眠らせ姫からの贈り物", title_hi: "ねむらせひめからのおくりもの", title_hangul: "네무라세히메카라노쿠리모노", length: 135 },
    { id: 351, name: "상생", title_jp: "相生", title_hi: "あいおい", title_hangul: "아이오이", length: 162 },
    { id: 352, name: "목숨뿐", title_jp: "命ばっかり", title_hi: "いのちばっかり", title_hangul: "이노치밧카리", length: 131 },
    { id: 353, name: "키티", title_jp: "キティ", title_hi: "きてぃ", title_hangul: "기테이", length: 114 },
    { id: 354, name: "세츠나 트립", title_jp: "セツナトリップ", title_hi: "せつなとりっぷ", title_hangul: "세쓰나토릿푸", length: 155 },
    { id: 355, name: "하얀 눈의 프린세스는", title_jp: "白い雪のプリンセスは", title_hi: "しろいゆきのぷりんせすは", title_hangul: "시로이유키노푸린세스하", length: 140 },
    { id: 356, name: "리얼라이즈", title_jp: "リアライズ", title_hi: "りあらいず", title_hangul: "리아라이즈", length: 94 },
    { id: 357, name: "블루 플래닛", title_jp: "ブループラネット", title_hi: "ぶるーぷらねっと", title_hangul: "부루푸라넷토", length: 136 },
    { id: 358, name: "마음탓", title_jp: "心做し", title_hi: "こころさくし", title_hangul: "고코로사쿠시", length: 139 },
    { id: 359, name: "이름 없는 혁명", title_jp: "名も無き革命", title_hi: "めいもなきかくめい", title_hangul: "메이모나키카쿠메이", length: 123 },
    { id: 360, name: "태양계 디스코", title_jp: "太陽系デスコ", title_hi: "たいようけいですこ", title_hangul: "다이요케이데스코", length: 146 },
    { id: 361, name: "두근 어질", title_jp: "きゅうくらりん", title_hi: "きゅうくらりん", title_hangul: "규쿠라린", length: 109 },
    { id: 362, name: "Wonder Style", title_jp: "Wonder Style", title_hi: "Wonder Style", title_hangul: "원더 스타일", length: 136 },
    { id: 363, name: "UNDERWATER", title_jp: "UNDERWATER", title_hi: "UNDERWATER", title_hangul: "언더워터", length: 149 },
    { id: 364, name: "이터널 아리아", title_jp: "エターナルアリア", title_hi: "えたーなるありあ", title_hangul: "에타나루아리아", length: 139 },
    { id: 365, name: "사랑은 전쟁", title_jp: "恋は戦争", title_hi: "こいはせんそう", title_hangul: "고이하센소", length: 143 },
    { id: 366, name: "NEO", title_jp: "NEO", title_hi: "NEO", title_hangul: "네오", length: 126 },
    { id: 367, name: "좋아하는 것만으로도 괜찮아요", title_jp: "すきなことだけでいいです", title_hi: "すきなことだけでいいです", title_hangul: "스키나코토다케데이데스", length: 155 },
    { id: 368, name: "아임 마인", title_jp: "アイムマイン", title_hi: "あいむまいん", title_hangul: "아이무마인", length: 157 },
    { id: 369, name: "멜랑콜릭", title_jp: "メランコリック", title_hi: "めらんこりっく", title_hangul: "메란코릿쿠", length: 148 },
    { id: 370, name: "인생", title_jp: "人生", title_hi: "じんせい", title_hangul: "진세이", length: 149 },
    { id: 372, name: "천악", title_jp: "天樂", title_hi: "てんがく", title_hangul: "덴가쿠", length: 151 },
    { id: 373, name: "하극상", title_jp: "下剋上", title_hi: "げこくじょう", title_hangul: "게코쿠조", length: 155 },
    { id: 374, name: "팀메이트", title_jp: "チームメイト", title_hi: "ちーむめいと", title_hangul: "지무메이토", length: 112 },
    { id: 375, name: "별을 잇다", title_jp: "星を繋ぐ", title_hi: "ほしをつなぐ", title_hangul: "호시오쓰나구", length: 97 },
    { id: 376, name: "제멋대로 공주", title_jp: "我儘姫", title_hi: "わがままひめ", title_hangul: "와가마마히메", length: 142 },
    { id: 377, name: "악역에게 키스신을", title_jp: "悪役にキスシーンを", title_hi: "あくやくにきすしーんを", title_hangul: "아쿠야쿠니키스신오", length: 153 },
    { id: 378, name: "슬로우 다우너", title_jp: "スロウダウナー", title_hi: "すろうだうなー", title_hangul: "스로다우나", length: 143 },
    { id: 379, name: "즌다 파티 나잇", title_jp: "ずんだパーリナイ", title_hi: "ずんだぱーりない", title_hangul: "즌다파리나이", length: 167 },
    { id: 380, name: "스타더스트 메들리", title_jp: "スターダストメドレー", title_hi: "すたーだすとめどれー", title_hangul: "스타다스토메도레", length: 143 },
    { id: 381, name: "신인류", title_jp: "新人類", title_hi: "しんじんるい", title_hangul: "신진루이", length: 157 },
    { id: 382, name: "심박 페어링", title_jp: "心拍ペアリング", title_hi: "しんぱくぺありんぐ", title_hangul: "신파쿠페아린구", length: 87 },
    { id: 383, name: "purpose", title_jp: "purpose", title_hi: "purpose", title_hangul: "퍼포즈", length: 109 },
    { id: 384, name: "트와일라잇 라이트", title_jp: "トワイライトライト", title_hi: "とわいらいとらいと", title_hangul: "도와이라이토라이토", length: 107 },
    { id: 385, name: "신 같네", title_jp: "神っぽいな", title_hi: "かみっぽいな", title_hangul: "가밋포이나", length: 148 },
    { id: 386, name: "키라피피★키라피카", title_jp: "キラピピ★キラピカ", title_hi: "きらぴぴ★きらぴか", title_hangul: "기라피피★키라피카", length: 102 },
    { id: 387, name: "Hello Builder", title_jp: "Hello Builder", title_hi: "Hello Builder", title_hangul: "헬로 빌더", length: 113 },
    { id: 390, name: "Dear", title_jp: "Dear", title_hi: "Dear", title_hangul: "디어", length: 150 },
    { id: 391, name: "큐트한 그녀", title_jp: "キュートなカノジョ", title_hi: "きゅーとなかのじょ", title_hangul: "규토나카노조", length: 132 },
    { id: 392, name: "춘람", title_jp: "春嵐", title_hi: "はるあらし", title_hangul: "하루아라시", length: 140 },
    { id: 393, name: "Un-Lock", title_jp: "Un-Lock", title_hi: "Un-Lock", title_hangul: "언락", length: 139 },
    { id: 394, name: "보틀케이크", title_jp: "ボトルケーキ", title_hi: "ぼとるけーき", title_hangul: "보토루케키", length: 116 },
    { id: 395, name: "서머타임 레코드", title_jp: "サマータイムレコード", title_hi: "さまーたいむれこーど", title_hangul: "사마타이무레코도", length: 149 },
    { id: 396, name: "도쿄 테디베어", title_jp: "東京テディベア", title_hi: "とうきょうてでぃべあ", title_hangul: "도쿄테데이베아", length: 135 },
    { id: 397, name: "필라멘트 피버", title_jp: "フィラメントフィーバー", title_hi: "ふぃらめんとふぃーばー", title_hangul: "후이라멘토후이바", length: 114 },
    { id: 398, name: "Beyond the way", title_jp: "Beyond the way", title_hi: "Beyond the way", title_hangul: "비욘드 더 웨이", length: 117 },
    { id: 399, name: "Disco No.39", title_jp: "Disco No.39", title_hi: "Disco No.39", title_hangul: "디스코 넘버.39", length: 134 },
    { id: 400, name: "우리들 스테인 버스터즈!", title_jp: "我らステインバスターズ！", title_hi: "われらすていんばすたーず！", title_hangul: "와레라스테인바스타즈！", length: 105 },
    { id: 401, name: "뜻대로", title_jp: "まにまに", title_hi: "まにまに", title_hangul: "마니마니", length: 114 },
    { id: 402, name: "엔비 베이비", title_jp: "エンヴィーベイビー", title_hi: "えんゔぃーべいびー", title_hangul: "엔ヴ이베이비", length: 137 },
    { id: 403, name: "츠가이코가라시", title_jp: "番凩", title_hi: "ばんこがらし", title_hangul: "반코가라시", length: 125 },
    { id: 404, name: "blender", title_jp: "blender", title_hi: "blender", title_hangul: "블렌더", length: 136 },
    { id: 405, name: "MOTTO!!!", title_jp: "MOTTO!!!", title_hi: "MOTTO!!!", title_hangul: "못또!!!", length: 142 },
    { id: 406, name: "ARQETYPE", title_jp: "ARQETYPE", title_hi: "ARQETYPE", title_hangul: "아키타입", length: 100 },
    { id: 407, name: "첫사랑이 끝날 때", title_jp: "初めての恋が終わる時", title_hi: "はじめてのこいがおわるとき", title_hangul: "하지메테노코이가오와루토키", length: 135 },
    { id: 408, name: "CIRCUS PANIC!!!", title_jp: "CIRCUS PANIC!!!", title_hi: "CIRCUS PANIC!!!", title_hangul: "서커스 패닉!!!", length: 138 },
    { id: 409, name: "25시의 정열", title_jp: "25時の情熱", title_hi: "25ときのじょうねつ", title_hangul: "25토키노조네쓰", length: 119 },
    { id: 410, name: "마셜 맥시마이저", title_jp: "マーシャル・マキシマイザー", title_hi: "まーしゃる・まきしまいざー", title_hangul: "마샤루・마키시마이자", length: 95 },
    { id: 411, name: "세계를 비추는 테트라드", title_jp: "世界を照らすテトラッド", title_hi: "せかいをてらすてとらっど", title_hangul: "세카이오테라스테토랏도", length: 122 },
    { id: 412, name: "데빌이 아닌걸", title_jp: "デビルじゃないもん", title_hi: "でびるじゃないもん", title_hangul: "데비루자나이몬", length: 121 },
    { id: 413, name: "안녕 프린세스", title_jp: "さよならプリンセス", title_hi: "さよならぷりんせす", title_hangul: "사요나라푸린세스", length: 119 },
    { id: 414, name: "HERO", title_jp: "HERO", title_hi: "HERO", title_hangul: "히어로", length: 123 },
    { id: 415, name: "럭키☆오브", title_jp: "ラッキー☆オーブ", title_hi: "らっきー☆おーぶ", title_hangul: "랏키☆오부", length: 121 },
    { id: 416, name: "limbo", title_jp: "limbo", title_hi: "limbo", title_hangul: "림보", length: 102 },
    { id: 417, name: "텅 비어가", title_jp: "くうになる", title_hi: "くうになる", title_hangul: "구니나루", length: 109 },
    { id: 418, name: "금목서", title_jp: "金木犀", title_hi: "きんもくせい", title_hangul: "긴모쿠세이", length: 124 },
    { id: 420, name: "imaginary love story", title_jp: "imaginary love story", title_hi: "imaginary love story", title_hangul: "이메지너리 러브 스토리", length: 129 },
    { id: 421, name: "CR에이ZY", title_jp: "CR詠ZY", title_hi: "CRえいZY", title_hangul: "크레이지", length: 103 },
    { id: 422, name: "JUMPIN’ OVER !", title_jp: "JUMPIN’ OVER !", title_hi: "JUMPIN’ OVER !", title_hangul: "점핀 오버!", length: 109 },
    { id: 423, name: "레굴루스", title_jp: "レグルス", title_hi: "れぐるす", title_hangul: "레구루스", length: 127 },
    { id: 424, name: "인티그럴", title_jp: "インテグラル", title_hi: "いんてぐらる", title_hangul: "인테구라루", length: 117 },
    { id: 425, name: "Cool Me Down", title_jp: "Cool Me Down", title_hi: "Cool Me Down", title_hangul: "쿨 미 다운", length: 149 },
    { id: 426, name: "On&On", title_jp: "On&On", title_hi: "On&On", title_hangul: "온 앤 온", length: 115 },
    { id: 427, name: "유광, 1/f의 흔들림", title_jp: "幽光、1/fのゆらめき", title_hi: "ゆうひかり、1/fのゆらめき", title_hangul: "유히카리、1f노유라메키", length: 91 },
    { id: 428, name: "두근두근 제트코스터", title_jp: "ときめきジェットコースター", title_hi: "ときめきじぇっとこーすたー", title_hangul: "도키메키지엣토코스타", length: 125 },
    { id: 429, name: "허그", title_jp: "はぐ", title_hi: "はぐ", title_hangul: "하구", length: 130 },
    { id: 430, name: "『응앗앗。』", title_jp: "『んっあっあっ。』", title_hi: "『んっあっあっ。』", title_hangul: "『은읏앗앗。』", length: 128 },
    { id: 431, name: "flos", title_jp: "flos", title_hi: "flos", title_hangul: "플로스", length: 125 },
    { id: 432, name: "강풍 올백", title_jp: "強風オールバック", title_hi: "きょうふうおーるばっく", title_hangul: "교후오루밧쿠", length: 137 },
    { id: 433, name: "불장난", title_jp: "ヒアソビ", title_hi: "ひあそび", title_hangul: "히아소비", length: 132 },
    { id: 434, name: "1000년 살고 있어", title_jp: "1000年生きてる", title_hi: "1000ねんせいきてる", title_hangul: "1000넨세이키테루", length: 108 },
    { id: 435, name: "릴레이아우터", title_jp: "リレイアウター", title_hi: "りれいあうたー", title_hangul: "리레이아우타", length: 153 },
    { id: 436, name: "고서저택 살인사건", title_jp: "古書屋敷殺人事件", title_hi: "こしょやしきさつじんじけん", title_hangul: "고쇼야시키사쓰진지켄", length: 122 },
    { id: 437, name: "응? 아아, 그래.", title_jp: "え？あぁ、そう。", title_hi: "え？あぁ、そう。", title_hangul: "에？아、소。", length: 111 },
    { id: 438, name: "하이드 앤 시크", title_jp: "ハイドアンド・シーク", title_hi: "はいどあんど・しーく", title_hangul: "하이도안도・시쿠", length: 125 },
    { id: 439, name: "일천광년", title_jp: "一千光年", title_hi: "いっせんこうねん", title_hangul: "잇센코넨", length: 116 },
    { id: 440, name: "쇼타임×오디언스", title_jp: "ショウタイム×オーディエンス", title_hi: "しょうたいむ×おーでぃえんす", title_hangul: "쇼타이무×오데이엔스", length: 123 },
    { id: 441, name: "취한 줄을 모르고", title_jp: "酔いどれ知らず", title_hi: "よいどれしらず", title_hangul: "요이도레시라즈", length: 136 },
    { id: 442, name: "스레스레", title_jp: "すれすれ", title_hi: "すれすれ", title_hangul: "스레스레", length: 97 },
    { id: 443, name: "사과팔이 물거품 소녀", title_jp: "林檎売りの泡沫少女", title_hi: "りんごうりのほうまつしょうじょ", title_hangul: "린고리노호마쓰쇼조", length: 130 },
    { id: 444, name: "심니몽(syndrome)", title_jp: "心泥夢(syndrome)", title_hi: "こころどろゆめ(syndrome)", title_hangul: "고코로도로유메(syndrome)", length: 161 },
    { id: 445, name: "Twilight Melody", title_jp: "Twilight Melody", title_hi: "Twilight Melody", title_hangul: "트와일라이트 멜로디", length: 137 },
    { id: 446, name: "오버 코드", title_jp: "オーバーコード", title_hi: "おーばーこーど", title_hangul: "오바코도", length: 160 },
    { id: 447, name: "folern", title_jp: "folern", title_hi: "folern", title_hangul: "폴른", length: 141 },
    { id: 448, name: "Sage", title_jp: "Sage", title_hi: "Sage", title_hangul: "사게", length: 151 },
    { id: 449, name: "MarbleBlue.", title_jp: "MarbleBlue.", title_hi: "MarbleBlue.", title_hangul: "마블블루.", length: 163 },
    { id: 450, name: "오페라! 스페이스 오페라!", title_jp: "オペラ！スペースオペラ！", title_hi: "おぺら！すぺーすおぺら！", title_hangul: "오페라！스페스오페라！", length: 126 },
    { id: 451, name: "열이상", title_jp: "熱異常", title_hi: "ねついじょう", title_hangul: "네쓰이조", length: 122 },
    { id: 452, name: "사이버펑크 데드 보이", title_jp: "サイバーパンクデッドボーイ", title_hi: "さいばーぱんくでっどぼーい", title_hangul: "사이바판쿠뎃도보이", length: 123 },
    { id: 454, name: "일렉트릭 엔젤", title_jp: "えれくとりっく・えんじぇぅ", title_hi: "えれくとりっく・えんじぇぅ", title_hangul: "에레쿠토릿쿠・엔지에우", length: 126 },
    { id: 455, name: "개쓰레기", title_jp: "ド屑", title_hi: "どくず", title_hangul: "도쿠즈", length: 121 },
    { id: 456, name: "기망의 달", title_jp: "幾望の月", title_hi: "きのぞのがつ", title_hangul: "기노조노가쓰", length: 125 },
    { id: 457, name: "Supernova", title_jp: "Supernova", title_hi: "Supernova", title_hangul: "슈퍼노바", length: 130 },
    { id: 458, name: "발묘", title_jp: "抜錨", title_hi: "ばつびょう", title_hangul: "바쓰뵤", length: 125 },
    { id: 460, name: "LEADER", title_jp: "LEADER", title_hi: "LEADER", title_hangul: "리더", length: 110 },
    { id: 461, name: "오도로보", title_jp: "おどロボ", title_hi: "おどろぼ", title_hangul: "오도로보", length: 164 },
    { id: 462, name: "레드 랜드 마커", title_jp: "レッドランドマーカー", title_hi: "れっどらんどまーかー", title_hangul: "렛도란도마카", length: 128 },
    { id: 463, name: "해피 치트 데이", title_jp: "ハッピーチートデー", title_hi: "はっぴーちーとでー", title_hangul: "핫피치토데", length: 122 },
    { id: 464, name: "Intergalactic Bound", title_jp: "Intergalactic Bound", title_hi: "Intergalactic Bound", title_hangul: "인터갈라틱 바운드", length: 127 },
    { id: 465, name: "양왕", title_jp: "嬢王", title_hi: "じょうおう", title_hangul: "조", length: 143 },
    { id: 466, name: "가넷의 눈물", title_jp: "ガーネットの涙", title_hi: "がーねっとのなみだ", title_hangul: "가넷토노나미다", length: 119 },
    { id: 467, name: "아이의노래", title_jp: "あいのうた", title_hi: "あいのうた", title_hangul: "아이노타", length: 123 },
    { id: 468, name: "열여섯 살의 심장", title_jp: "十六歳の心臓", title_hi: "じゅうろくさいのしんぞう", title_hangul: "주로쿠사이노신조", length: 136 },
    { id: 469, name: "래그 트레인", title_jp: "ラグトレイン", title_hi: "らぐとれいん", title_hangul: "라구토레인", length: 127 },
    { id: 470, name: "첫 소리", title_jp: "ハジメテノオト", title_hi: "はじめてのおと", title_hangul: "하지메테노토", length: 131 },
    { id: 471, name: "ULTRA C", title_jp: "ULTRA C", title_hi: "ULTRA C", title_hangul: "울트라 씨", length: 97 },
    { id: 472, name: "처단하겠다AAAAA!", title_jp: "成敗いたAAAAAす！", title_hi: "せいばいいたAAAAAす！", title_hangul: "세이바이타AAAAA스！", length: 133 },
    { id: 473, name: "마인드 브랜드", title_jp: "マインドブランド", title_hi: "まいんどぶらんど", title_hangul: "마인도부란도", length: 125 },
    { id: 474, name: "키라", title_jp: "キラー", title_hi: "きらー", title_hangul: "기라", length: 98 },
    { id: 475, name: "달라!!!", title_jp: "ちがう!!!", title_hi: "ちがう!!!", title_hangul: "지가우!!!", length: 118 },
    { id: 476, name: "Shadow Shadow", title_jp: "Shadow Shadow", title_hi: "Shadow Shadow", title_hangul: "섀도우 섀도우", length: 129 },
    { id: 477, name: "모자이크 롤 (Reloaded)", title_jp: "モザイクロール (Reloaded)", title_hi: "もざいくろーる (Reloaded)", title_hangul: "모자이쿠로루 (Reloaded)", length: 125 },
    { id: 478, name: "퓨얼", title_jp: "フューエル", title_hi: "ふゅーえる", title_hangul: "후우에루", length: 102 },
    { id: 480, name: "장난기 기능", title_jp: "おちゃめ機能", title_hi: "おちゃめきのう", title_hangul: "오차메키노", length: 126 },
    { id: 481, name: "명경지수", title_jp: "明鏡止水", title_hi: "めいきょうしすい", title_hangul: "메이쿄시스이", length: 123 },
    { id: 482, name: "답 없는 인간이다!", title_jp: "だめにんげんだ!", title_hi: "だめにんげんだ!", title_hangul: "다메닌겐다!", length: 122 },
    { id: 483, name: "아코토바", title_jp: "アコトバ", title_hi: "あことば", title_hangul: "아코토바", length: 130 },
    { id: 484, name: "Henceforth", title_jp: "Henceforth", title_hi: "Henceforth", title_hangul: "헨스포스", length: 126 },
    { id: 485, name: "점점 빨라져", title_jp: "だんだん早くなる", title_hi: "だんだんはやくなる", title_hangul: "단단하야쿠나루", length: 141 },
    { id: 486, name: "오갸리나이저", title_jp: "おぎゃりないざー", title_hi: "おぎゃりないざー", title_hangul: "오갸리나이자", length: 128 },
    { id: 487, name: "괜찮으신가요?", title_jp: "ダイジョブですか？", title_hi: "だいじょぶですか？", title_hangul: "다이조부데스카？", length: 151 },
    { id: 488, name: "메모리아", title_jp: "メモリア", title_hi: "めもりあ", title_hangul: "메모리아", length: 160 },
    { id: 489, name: "열풍", title_jp: "熱風", title_hi: "ねっぷう", title_hangul: "넷푸", length: 113 },
    { id: 490, name: "루머", title_jp: "ルーマー", title_hi: "るーまー", title_hangul: "루마", length: 123 },
    { id: 491, name: "캣 러빙", title_jp: "キャットラビング", title_hi: "きゃっとらびんぐ", title_hangul: "걋토라빈구", length: 118 },
    { id: 492, name: "나는 비", title_jp: "私は雨", title_hi: "わたしはあめ", title_hangul: "와타시하메", length: 125 },
    { id: 493, name: "오늘도 상쾌하게", title_jp: "きょうもハレバレ", title_hi: "きょうもはればれ", title_hangul: "교모하레바레", length: 121 },
    { id: 494, name: "팝핀캔디☆피버!", title_jp: "ポッピンキャンディ☆フィーバー！", title_hi: "ぽっぴんきゃんでぃ☆ふぃーばー！", title_hangul: "폿핀캰데이☆후이바！", length: 129 },
    { id: 495, name: "슈퍼히어로", title_jp: "スーパーヒーロー", title_hi: "すーぱーひーろー", title_hangul: "스파히로", length: 115 },
    { id: 496, name: "실버 콜렉터", title_jp: "シルバーコレクター", title_hi: "しるばーこれくたー", title_hangul: "시루바코레쿠타", length: 132 },
    { id: 497, name: "열화", title_jp: "烈火", title_hi: "れっか", title_hangul: "렛카", length: 140 },
    { id: 498, name: "달려라! 저 멀리! 닿아라!", title_jp: "はしる! とおく! とどく!", title_hi: "はしる! とおく! とどく!", title_hangul: "하시루! 도쿠! 도도쿠!", length: 109 },
    { id: 499, name: "혼돈 부기", title_jp: "混沌ブギ", title_hi: "こんとんぶぎ", title_hangul: "곤톤부기", length: 124 },
    { id: 500, name: "여화에 넋을 잃고", title_jp: "余花にみとれて", title_hi: "よかにみとれて", title_hangul: "요카니미토레테", length: 130 },
    { id: 501, name: "Bad Apple!! feat.SEKAI", title_jp: "Bad Apple!! feat.SEKAI", title_hi: "Bad Apple!! feat.SEKAI", title_hangul: "배드 애플!!! 피처링.세카이", length: 146 },
    { id: 502, name: "Help me, ERINNNNNN!!", title_jp: "Help me, ERINNNNNN!!", title_hi: "Help me, ERINNNNNN!!", title_hangul: "헬프 미, 에린ㄴㄴㄴ!!", length: 146 },
    { id: 503, name: "최종귀축 여동생 플랑드르 S", title_jp: "超最終鬼畜妹フランドール・Ｓ", title_hi: "ちょうさいしゅうきちくいもうとふらんどーる・Ｓ", title_hangul: "조사이슈키치쿠이모토후란도루・Ｓ", length: 123 },
    { id: 504, name: "I know 愛脳.", title_jp: "I know 愛脳.", title_hi: "I know あいのう.", title_hangul: "아이 노 아이노오", length: 122 },
    { id: 505, name: "콜보이", title_jp: "コールボーイ", title_hi: "こーるぼーい", title_hangul: "고루보이", length: 124 },
    { id: 506, name: "QUEEN", title_jp: "QUEEN", title_hi: "QUEEN", title_hangul: "퀸", length: 144 },
    { id: 507, name: "엠퍼플", title_jp: "エンパープル", title_hi: "えんぱーぷる", title_hangul: "엔파푸루", length: 119 },
    { id: 508, name: "헤이븐", title_jp: "ヘイヴン", title_hi: "へいゔん", title_hangul: "헤이ヴ은", length: 117 },
    { id: 509, name: "라이어 댄서", title_jp: "ライアーダンサー", title_hi: "らいあーだんさー", title_hangul: "라이아단사", length: 123 },
    { id: 510, name: "실패작 소녀", title_jp: "失敗作少女", title_hi: "しっぱいさくしょうじょ", title_hangul: "싯파이사쿠쇼조", length: 126 },
    { id: 511, name: "키사라기 어텐션", title_jp: "如月アテンション", title_hi: "きさらぎあてんしょん", title_hangul: "기사라기아텐숀", length: 118 },
    { id: 512, name: "합성하는 미래", title_jp: "合成するミライ", title_hi: "ごうせいするみらい", title_hangul: "고세이스루미라이", length: 135 },
    { id: 513, name: "CH4NGE", title_jp: "CH4NGE", title_hi: "CH4NGE", title_hangul: "체인지", length: 135 },
    { id: 515, name: "의학", title_jp: "イガク", title_hi: "いがく", title_hangul: "이가쿠", length: 121 },
    { id: 516, name: "여기저기 데이트 씨", title_jp: "あちこちデートさん", title_hi: "あちこちでーとさん", title_hangul: "아치코치데토산", length: 122 },
    { id: 517, name: "메리 고 라운드", title_jp: "メリーゴーラウンド", title_hi: "めりーごーらうんど", title_hangul: "메리고라운도", length: 139 },
    { id: 518, name: "금성", title_jp: "みかぼし", title_hi: "みかぼし", title_hangul: "미카보시", length: 131 },
    { id: 519, name: "여름밤의 노래", title_jp: "夏夜ノ唄", title_hi: "なつよるのうた", title_hangul: "나쓰요루노타", length: 122 },
    { id: 520, name: "투명 엘레지", title_jp: "透明エレジー", title_hi: "とうめいえれじー", title_hangul: "도메이에레지", length: 123 },
    { id: 521, name: "오버라이드", title_jp: "オーバーライド", title_hi: "おーばーらいど", title_hangul: "오바라이도", length: 120 },
    { id: 522, name: "WAVE", title_jp: "WAVE", title_hi: "WAVE", title_hangul: "웨이브", length: 117 },
    { id: 523, name: "너와 나의 레조넌스", title_jp: "きみとぼくのレゾナンス", title_hi: "きみとぼくのれぞなんす", title_hangul: "기미토보쿠노레조난스", length: 132 },
    { id: 524, name: "그럼에도 우리는 노래하는 것을 그만두지 않아", title_jp: "それでも僕らは歌うことをやめない", title_hi: "それでもぼくらはうたうことをやめない", title_hangul: "소레데모보쿠라하우타우코토야메나이", length: 98 },
    { id: 525, name: "안테나39", title_jp: "アンテナ39", title_hi: "あんてな39", title_hangul: "안테나39", length: 126 },
    { id: 526, name: "혜성의 은하", title_jp: "彗星ノ銀河", title_hi: "すいせいのぎんが", title_hangul: "스이세이노긴가", length: 124 },
    { id: 527, name: "Unpoison", title_jp: "Unpoison", title_hi: "Unpoison", title_hangul: "언포이즌", length: 122 },
    { id: 529, name: "컬처", title_jp: "カルチャ", title_hi: "かるちゃ", title_hangul: "가루차", length: 109 },
    { id: 530, name: "캣 푸드", title_jp: "キャットフード", title_hi: "きゃっとふーど", title_hangul: "걋토후도", length: 122 },
    { id: 531, name: "메스머라이저", title_jp: "メズマライザー", title_hi: "めずまらいざー", title_hangul: "메즈마라이자", length: 126 },
    { id: 532, name: "레이어 노트", title_jp: "レイヤーノート", title_hi: "れいやーのーと", title_hangul: "레이야노토", length: 128 },
    { id: 533, name: "전생사과", title_jp: "転生林檎", title_hi: "てんしょうりんご", title_hangul: "덴쇼린고", length: 113 },
    { id: 534, name: "월드 램프 쉐이드 [reunion]", title_jp: "ワールド・ランプシェード [reunion]", title_hi: "わーるど・らんぷしぇーど [reunion]", title_hangul: "와루도・란푸시에도 [reunion]", length: 129 },
    { id: 536, name: "Fire◎Flower (Rerec)", title_jp: "Fire◎Flower (Rerec)", title_hi: "Fire◎Flower (Rerec)", title_hangul: "파이어◎플라워 (Rerec)", length: 104 },
    { id: 537, name: "꽃에 바람", title_jp: "花に風", title_hi: "はなにかぜ", title_hangul: "하나니카제", length: 129 },
    { id: 538, name: "올 세이브 챌린지", title_jp: "オールセーブチャレンジ", title_hi: "おーるせーぶちゃれんじ", title_hangul: "오루세부차렌지", length: 97 },
    { id: 539, name: "일레븐스", title_jp: "イレヴンス", title_hi: "いれゔんす", title_hangul: "이레ヴ은스", length: 98 },
    { id: 540, name: "허무 씨", title_jp: "虚無さん", title_hi: "きょむさん", title_hangul: "교무산", length: 94 },
    { id: 541, name: "메인 캐릭터", title_jp: "メインキャラクター", title_hi: "めいんきゃらくたー", title_hangul: "메인캬라쿠타", length: 115 },
    { id: 542, name: "Blackjack", title_jp: "Blackjack", title_hi: "Blackjack", title_hangul: "블랙잭", length: 130 },
    { id: 543, name: "생명성 신드롬", title_jp: "生命性シンドロウム", title_hi: "せいめいせいしんどろうむ", title_hangul: "세이메이세이신도로무", length: 133 },
    { id: 544, name: "망상 아스파탐", title_jp: "妄想アスパルテーム", title_hi: "もうそうあすぱるてーむ", title_hangul: "모소아스파루테무", length: 119 },
    { id: 545, name: "정수리", title_jp: "脳天", title_hi: "のうてん", title_hangul: "노텐", length: 116 },
    { id: 546, name: "그 소리가 울린다면", title_jp: "その音が鳴るなら", title_hi: "そのおとがなるなら", title_hangul: "소노토가나루나라", length: 111 },
    { id: 547, name: "종언도피행", title_jp: "終焉逃避行", title_hi: "しゅうえんとうひこう", title_hangul: "슈엔토히코", length: 100 },
    { id: 548, name: "나의 신님", title_jp: "ぼくのかみさま", title_hi: "ぼくのかみさま", title_hangul: "보쿠노카미사마", length: 124 },
    { id: 549, name: "둔갑의 꽃", title_jp: "化けの花", title_hi: "ばけのはな", title_hangul: "바케노하나", length: 118 },
    { id: 551, name: "로스트 엄브렐라", title_jp: "ロストアンブレラ", title_hi: "ろすとあんぶれら", title_hangul: "로스토안부레라", length: 122 },
    { id: 552, name: "M@GICAL☆CURE! LOVE ♥ SHOT!", title_jp: "M@GICAL☆CURE! LOVE ♥ SHOT!", title_hi: "M@GICAL☆CURE! LOVE ♥ SHOT!", title_hangul: "매@지컬☆큐트! 러브 ♥ 샷!", length: 129 },
    { id: 553, name: "패리", title_jp: "パリィ", title_hi: "ぱりぃ", title_hangul: "파리", length: 124 },
    { id: 554, name: "snooze", title_jp: "snooze", title_hi: "snooze", title_hangul: "스누즈", length: 127 },
    { id: 555, name: "퓨전", title_jp: "フュージョン", title_hi: "ふゅーじょん", title_hangul: "후우존", length: 124 },
    { id: 556, name: "사이하테", title_jp: "サイハテ", title_hi: "さいはて", title_hangul: "사이하테", length: 131 },
    { id: 557, name: "꽃에 빠지다", title_jp: "花溺れ", title_hi: "はなおぼれ", title_hangul: "하나오보레", length: 126 },
    { id: 558, name: "것이다", title_jp: "のだ", title_hi: "のだ", title_hangul: "노다", length: 121 },
    { id: 559, name: "춤춰라", title_jp: "おどりゃんせ", title_hi: "おどりゃんせ", title_hangul: "오도랸세", length: 131 },
    { id: 560, name: "아이리드", title_jp: "アイリッド", title_hi: "あいりっど", title_hangul: "아이릿도", length: 123 },
    { id: 561, name: "프로토 디스코", title_jp: "プロトディスコ", title_hi: "ぷろとでぃすこ", title_hangul: "푸로토데이스코", length: 130 },
    { id: 562, name: "앙헬", title_jp: "アンヘル", title_hi: "あんへる", title_hangul: "안헤루", length: 125 },
    { id: 564, name: "그곳에 있는, 빛.", title_jp: "そこに在る、光。", title_hi: "そこにある、ひかり。", title_hangul: "소코니아루、히카리。", length: 96 },
    { id: 565, name: "여름에 투명", title_jp: "夏に透明", title_hi: "なつにとうめい", title_hangul: "나쓰니토메이", length: 121 },
    { id: 566, name: "판다 히어로", title_jp: "パンダヒーロー", title_hi: "ぱんだひーろー", title_hangul: "판다히로", length: 100 },
    { id: 567, name: "쥐었다가 펼쳐서 나찰과 송장", title_jp: "結ンデ開イテ羅刹ト骸", title_hi: "けつんでかいいてらせつとむくろ", title_hangul: "게쓴데카이테라세쓰토무쿠로", length: 130 },
    { id: 569, name: "시크릿 시커", title_jp: "シークレット・シーカー", title_hi: "しーくれっと・しーかー", title_hangul: "시쿠렛토・시카", length: 115 },
    { id: 570, name: "스타", title_jp: "スター", title_hi: "すたー", title_hangul: "스타", length: 111 },
    { id: 571, name: "가짜인간40호", title_jp: "偽物人間40号", title_hi: "にせものにんげん40ごう", title_hangul: "니세모노닌겐40고", length: 127 },
    { id: 572, name: "장식하며", title_jp: "飾って", title_hi: "かざって", title_hangul: "가잣테", length: 126 },
    { id: 573, name: "시작의 미래", title_jp: "はじまりの未来", title_hi: "はじまりのみらい", title_hangul: "하지마리노미라이", length: 135 },
    { id: 574, name: "SToRY", title_jp: "SToRY", title_hi: "SToRY", title_hangul: "스토리", length: 97 },
    { id: 575, name: "FUN!!", title_jp: "FUN!!", title_hi: "FUN!!", title_hangul: "펀!!", length: 95 },
    { id: 576, name: "파이어 댄스", title_jp: "ファイアダンス", title_hi: "ふぁいあだんす", title_hangul: "후아이아단스", length: 92 },
    { id: 577, name: "스마일*심포니", title_jp: "スマイル*シンフォニー", title_hi: "すまいる*しんふぉにー", title_hangul: "스마이루*신후오니", length: 94 },
    { id: 578, name: "헬로 세카이", title_jp: "ハローセカイ", title_hi: "はろーせかい", title_hangul: "하로세카이", length: 105 },
    { id: 579, name: "Worlders", title_jp: "Worlders", title_hi: "Worlders", title_hangul: "월더스", length: 133 },
    { id: 580, name: "초승달 스텝", title_jp: "三日月ステップ", title_hi: "みかづきすてっぷ", title_hangul: "미카즈키스텟푸", length: 122 },
    { id: 581, name: "중병격발 보이", title_jp: "厨病激発ボーイ", title_hi: "ずびょうげきはつぼーい", title_hangul: "즈뵤게키하쓰보이", length: 131 },
    { id: 582, name: "안티 유", title_jp: "アンチユー", title_hi: "あんちゆー", title_hangul: "안치유", length: 120 },
    { id: 583, name: "액셀러레이트", title_jp: "アクセラレイト", title_hi: "あくせられいと", title_hangul: "아쿠세라레이토", length: 102 },
    { id: 584, name: "IMAWANOKIWA", title_jp: "IMAWANOKIWA", title_hi: "IMAWANOKIWA", title_hangul: "이마와노키와", length: 137 },
    { id: 585, name: "펜타토닉", title_jp: "ペンタトニック", title_hi: "ぺんたとにっく", title_hangul: "펜타토닛쿠", length: 107 },
    { id: 587, name: "룰 북", title_jp: "ルルブ", title_hi: "るるぶ", title_hangul: "루루부", length: 125 },
    { id: 588, name: "플래닛 히어로", title_jp: "プラネットヒーロー", title_hi: "ぷらねっとひーろー", title_hangul: "푸라넷토히로", length: 121 },
    { id: 589, name: "발레리코", title_jp: "バレリーコ", title_hi: "ばれりーこ", title_hangul: "바레리코", length: 129 },
    { id: 590, name: "맨해튼", title_jp: "マンハッタン", title_hi: "まんはったん", title_hangul: "만핫탄", length: 131 },
    { id: 591, name: "요시하라 라멘토", title_jp: "吉原ラメント 再来盤", title_hi: "よしはららめんと さいらいばん", title_hangul: "요시하라라멘토 사이라이반", length: 137 },
    { id: 592, name: "퀸 오브 하트", title_jp: "クイーンオブハート", title_hi: "くいーんおぶはーと", title_hangul: "구인오부하토", length: 125 },
    { id: 593, name: "크리스털 스노우", title_jp: "クリスタルスノウ", title_hi: "くりすたるすのう", title_hangul: "구리스타루스노", length: 105 },
    { id: 594, name: "Call!!", title_jp: "Call!!", title_hi: "Call!!", title_hangul: "콜!!!", length: 102 },
    { id: 595, name: "엔비 캣워크", title_jp: "エンヴィキャットウォーク", title_hi: "えんゔぃきゃっとうぉーく", title_hangul: "엔ヴ이캿토쿠", length: 131 },
    { id: 596, name: "D/N/A", title_jp: "D/N/A", title_hi: "D/N/A", title_hangul: "D/N/A", length: 129 },
    { id: 597, name: "그 그림의 이름은", title_jp: "その絵の名前は", title_hi: "そのえのなまえは", title_hangul: "소노에노나마에하", length: 125 },
    { id: 600, name: "나아가라", title_jp: "征け", title_hi: "ゆけ", title_hangul: "유케", length: 112 },
    { id: 601, name: "루마", title_jp: "ルマ", title_hi: "るま", title_hangul: "루마", length: 129 },
    { id: 603, name: "도레미파 론도", title_jp: "ドレミファロンド", title_hi: "どれみふぁろんど", title_hangul: "도레미후아론도", length: 130 },
    { id: 604, name: "Packaged", title_jp: "Packaged", title_hi: "Packaged", title_hangul: "패키지드", length: 129 },
    { id: 605, name: "Sympathy", title_jp: "Sympathy", title_hi: "Sympathy", title_hangul: "심파시", length: 98 },
    { id: 606, name: "수어사이드 퍼레이드", title_jp: "スーサイドパレヱド", title_hi: "すーさいどぱれゑど", title_hangul: "스사이도파레ヱ도", length: 116 },
    { id: 607, name: "회전하는 하늘 토끼", title_jp: "回る空うさぎ", title_hi: "まわるそらうさぎ", title_hangul: "마와루소라우사기", length: 132 },
    { id: 608, name: "별우주 멜랑콜리아", title_jp: "星宙メランコリア", title_hi: "ほしちゅうめらんこりあ", title_hangul: "호시추메란코리아", length: 123 },
    { id: 619, name: "Connecting", title_jp: "Connecting", title_hi: "Connecting", title_hangul: "커넥팅", length: 123 },
    { id: 620, name: "사마", title_jp: "紗痲", title_hi: "さま", title_hangul: "사마", length: 130 },
    { id: 621, name: "도쿄 서머 세션", title_jp: "東京サマーセッション", title_hi: "とうきょうさまーせっしょん", title_hangul: "도쿄사마셋숀", length: 133 },
    { id: 622, name: "초나이트 오브 나이츠", title_jp: "超ナイト・オブ・ナイツ", title_hi: "ちょうないと・おぶ・ないつ", title_hangul: "조나이토・오부・나이쓰", length: 131 },
    { id: 623, name: "동방☆원더랜드", title_jp: "とうほう☆ワンダーランド", title_hi: "とうほう☆わんだーらんど", title_hangul: "도호☆완다란도", length: 112 },
    { id: 624, name: "치르노의 퍼펙트 산수학원", title_jp: "チルノのパーフェクトさんすう学園", title_hi: "ちるののぱーふぇくとさんすうがくえん", title_hangul: "지루노노파후에쿠토산스가쿠엔", length: 127 },
    { id: 625, name: "이 실없이 멋진 세계는, 나를 위해 있어", title_jp: "このふざけた素晴らしき世界は、僕の為にある", title_hi: "このふざけたすばらしきせかいは、ぼくのためにある", title_hangul: "고노후자케타스바라시키세카이하、보쿠노타메니아루", length: 123 },
    { id: 626, name: "피쉬 앤 Tips", title_jp: "フィッシュアンドTips", title_hi: "ふぃっしゅあんどTips", title_hangul: "후잇슈안도Tips", length: 123 },
    { id: 627, name: "테토리스", title_jp: "テトリス", title_hi: "てとりす", title_hangul: "데토리스", length: 94 },
    { id: 628, name: "모니터링", title_jp: "モニタリング", title_hi: "もにたりんぐ", title_hangul: "모니타린구", length: 133 },
    { id: 629, name: "8.32", title_jp: "8.32", title_hi: "8.32", title_hangul: "8.32", length: 121 },
    { id: 632, name: "Surges", title_jp: "Surges", title_hi: "Surges", title_hangul: "서지", length: 134 },
    { id: 633, name: "정원사의 말에 따르면", title_jp: "庭師のおはなしによると", title_hi: "にわしのおはなしによると", title_hangul: "니와시노하나시니요루토", length: 117 },
    { id: 634, name: "광선가", title_jp: "光線歌", title_hi: "こうせんうた", title_hangul: "고센우타", length: 120 },
    { id: 635, name: "있는 그대로의 이야기를", title_jp: "ありのままのストーリーを", title_hi: "ありのままのすとーりーを", title_hangul: "아리노마마노스토리오", length: 108 },
    { id: 636, name: "익스플로어", title_jp: "エクスプロウル", title_hi: "えくすぷろうる", title_hangul: "에쿠스푸로루", length: 125 },
    { id: 637, name: "웃으면 좋다 아이가!", title_jp: "笑えたらえーやん！", title_hi: "わらえたらえーやん！", title_hangul: "와라에타라에얀！", length: 125 },
    { id: 638, name: "꽃잎, 그것에 얽힌 음성", title_jp: "花弁、それにまつわる音声", title_hi: "かべん、それにまつわるおんせい", title_hangul: "가벤、소레니마쓰와루온세이", length: 131 },
    { id: 639, name: "마리오네트 댄서", title_jp: "マリオネットダンサー", title_hi: "まりおねっとだんさー", title_hangul: "마리오넷토단사", length: 127 },
    { id: 644, name: "살다", title_jp: "生きる", title_hi: "いきる", title_hangul: "이키루", length: 102 },
    { id: 645, name: "심해시티 언더그라운드", title_jp: "深海シティアンダーグラウンド", title_hi: "しんかいしてぃあんだーぐらうんど", title_hangul: "신카이시테이안다구라운도", length: 129 },
    { id: 646, name: "투명한 팔레트", title_jp: "透明なパレット", title_hi: "とうめいなぱれっと", title_hangul: "도메이나파렛토", length: 111 },
    { id: 647, name: "SAN치 직장", title_jp: "SAN値直葬", title_hi: "SANあたいちょくそう", title_hangul: "SAN아타이초쿠소", length: 150 },
    { id: 648, name: "Life Will Change", title_jp: "Life Will Change", title_hi: "Life Will Change", title_hangul: "라이프 윌 체인지", length: 127 },
    { id: 649, name: "잘 있어 천국 다시 와줘 지옥", title_jp: "サヨナラ天国また来て地獄", title_hi: "さよならてんごくまたきてじごく", title_hangul: "사요나라텐고쿠마타키테지고쿠", length: 110 },
    { id: 650, name: "그 여름이 포화한다.", title_jp: "あの夏が飽和する。", title_hi: "あのなつがほうわする。", title_hangul: "아노나쓰가호와스루。", length: 126 },
    { id: 651, name: "화이트 해피", title_jp: "ホワイトハッピー", title_hi: "ほわいとはっぴー", title_hangul: "호와이토핫피", length: 127 },
    { id: 652, name: "남자친구의 주드", title_jp: "カレシのジュード", title_hi: "かれしのじゅーど", title_hangul: "가레시노주도", length: 136 },
    { id: 653, name: "파멜라", title_jp: "パメラ", title_hi: "ぱめら", title_hangul: "파메라", length: 133 },
    { id: 654, name: "러스트러스", title_jp: "ラストラス", title_hi: "らすとらす", title_hangul: "라스토라스", length: 133 },
    { id: 655, name: "릴리라라", title_jp: "リリィララ", title_hi: "りりぃらら", title_hangul: "리리라라", length: 124 },
    { id: 656, name: "블러드 돌", title_jp: "ブラッドドール", title_hi: "ぶらっどどーる", title_hangul: "부랏도도루", length: 123 },
    { id: 659, name: "당신의 하늘이 운다면", title_jp: "あなたの空が泣くのなら", title_hi: "あなたのそらがなくのなら", title_hangul: "아나타노소라가나쿠노나라", length: 127 },
    { id: 663, name: "비너스", title_jp: "ヴィーナス", title_hi: "ゔぃーなす", title_hangul: "ヴ이나스", length: 133 },
    { id: 664, name: "사람 마니아", title_jp: "人マニア", title_hi: "にんまにあ", title_hangul: "닌마니아", length: 130 },
    { id: 665, name: "로켓 사이다", title_jp: "ロケットサイダー", title_hi: "ろけっとさいだー", title_hangul: "로켓토사이다", length: 132 },
    { id: 666, name: "소녀A", title_jp: "少女A", title_hi: "しょうじょA", title_hangul: "쇼조A", length: 136 },
    { id: 667, name: "(무)책임집합체", title_jp: "㋰責任集合体", title_hi: "㋰せきにんしゅうごうたい", title_hangul: "㋰세키닌슈고타이", length: 122 },
    { id: 668, name: "네크라튠 서커스", title_jp: "ネクラチューンサーカス", title_hi: "ねくらちゅーんさーかす", title_hangul: "네쿠라춘사카스", length: 127 },
    { id: 669, name: "원점", title_jp: "げんてん", title_hi: "げんてん", title_hangul: "겐텐", length: 131 },
    { id: 670, name: "됐~어 됐~어 됐~어", title_jp: "い〜やい〜やい〜や", title_hi: "い〜やい〜やい〜や", title_hangul: "이〜야이〜야이〜야", length: 130 },
    { id: 671, name: "괴수가 되고 싶어", title_jp: "怪獣になりたい", title_hi: "かいじゅうになりたい", title_hangul: "가이주니나리타이", length: 125 },
    { id: 672, name: "하우 투 세계정복", title_jp: "ハウトゥー世界征服", title_hi: "はうとぅーせかいせいふく", title_hangul: "하우토세카이세이후쿠", length: 121 },
    { id: 677, name: "아벨리아", title_jp: "アベリア", title_hi: "あべりあ", title_hangul: "아베리아", length: 120 },
    { id: 678, name: "금시계", title_jp: "金時計", title_hi: "きんどけい", title_hangul: "긴도케이", length: 100 },
    { id: 684, name: "파이터", title_jp: "ファイター", title_hi: "ふぁいたー", title_hangul: "후아이타", length: 107 },
    { id: 685, name: "전광찰가", title_jp: "電光刹歌", title_hi: "でんこうさつうた", title_hangul: "덴코사쓰타", length: 132 },
    { id: 686, name: "트레저 가든", title_jp: "トレジャーガーデン", title_hi: "とれじゃーがーでん", title_hangul: "도레자가덴", length: 131 },
    { id: 687, name: "제트 블랙", title_jp: "ジェットブラック", title_hi: "じぇっとぶらっく", title_hangul: "지엣토부랏쿠", length: 131 },
    { id: 688, name: "위 아 피코피코 해머즈!!!!", title_jp: "ウィーアーピコピコハンマーズ!!!!", title_hi: "うぃーあーぴこぴこはんまーず!!!!", title_hangul: "우이아피코피코한마즈!!!!", length: 126 },
    { id: 689, name: "최애 인생 러너", title_jp: "最愛人生ランナー", title_hi: "さいあいじんせいらんなー", title_hangul: "사이아이진세이란나", length: 116 },
    { id: 691, name: "0.0000034", title_jp: "0.0000034", title_hi: "0.0000034", title_hangul: "0.0000034", length: 154 },
    { id: 695, name: "꽃매듭", title_jp: "花結び", title_hi: "はなむすび", title_hangul: "하나무스비", length: 125 },
];
