export const SONG_OPTIONS = [
    { id: 43, name: '넥스트 네스트', title_jp: 'ネクストネスト' },
    { id: 47, name: '멜트', title_jp: 'メルト' },
    { id: 49, name: '하츠네 미쿠의 소실', title_jp: '初音ミクの消失' },
    { id: 50, name: '블레싱', title_jp: 'Blessing' },
    { id: 82, name: '얼라이브', title_jp: 'alive' },
    { id: 2, name: '로키', title_jp: 'ロキ' },
    { id: 3, name: '테오', title_jp: 'テオ' },
    { id: 6, name: '히바나', title_jp: 'ヒバナ -Reloaded-' },
    { id: 10, name: '해피 신디사이저', title_jp: 'ハッピーシンセサイザ' },
    { id: 13, name: '노스텔로직', title_jp: 'Nostalogic' },
    { id: 71, name: '누덕누덕 스타카토', title_jp: 'ツギハギスタッカート' },
    { id: 26, name: '열등상등', title_jp: '劣等上等' },
    { id: 28, name: '닥터=펑크 비트', title_jp: 'ドクター＝ファンクビート' },
    { id: 69, name: '프래질', title_jp: 'フラジール' },
    { id: 38, name: '브리키의 댄스', title_jp: 'ブリキノダンス' },
    { id: 41, name: '스위트 매직', title_jp: 'スイートマジック' },
    { id: 78, name: '모험의 서가 사라졌습니다!', title_jp: 'ぼうけんのしょがきえました！' },
    { id: 19, name: '샤를', title_jp: 'シャルル' },
    { id: 66, name: '하로/하와유', title_jp: 'ハロ／ハワユ' },
    { id: 67, name: '자상무색', title_jp: '自傷無色' },
    { id: 63, name: '니들', title_jp: 'needLe' },
    { id: 57, name: '아이돌 신예대', title_jp: 'アイドル新鋭隊' },
    { id: 54, name: '레디 스테디', title_jp: 'Ready Steady' },
    { id: 51, name: '세상은 아직 시작조차 하지 않았어', title_jp: 'セカイはまだ始まってすらいない' },
    { id: 60, name: '후회한다 쓰고 미래', title_jp: '悔やむと書いてミライ' },
    { id: 76, name: '세카이', title_jp: 'セカイ' },
    { id: 77, name: '와 와 월드', title_jp: 'ワーワーワールド' },
    { id: 18, name: '내일의 밤하늘 초계반', title_jp: 'アスノヨゾラ哨戒班' },
    { id: 73, name: '니아', title_jp: 'ニア' },
    { id: 27, name: '저스트 비 프렌즈', title_jp: 'Just Be Friends' },
    { id: 21, name: '탈법 록', title_jp: '脱法ロック' },
    { id: 22, name: '생명에게 미움받고 있어.', title_jp: '命に嫌われている' },
    { id: 48, name: '월드 이즈 마인', title_jp: 'ワールドイズマイン' },
    { id: 68, name: '댄스 로봇 댄스', title_jp: 'ダンスロボットダンス' },
    { id: 44, name: '핸드 인 핸드', title_jp: 'Hand in Hand' },
    { id: 81, name: '야화 디세이브', title_jp: '夜咄ディセイブ' },
    { id: 83, name: '김미x김미', title_jp: 'Gimme×Gimme' },
    { id: 11, name: '비바해피', title_jp: 'ビバハピ' },
    { id: 84, name: '정키 나이트 타운 오케스트라', title_jp: 'ジャンキーナイトタウンオーケストラ' },
    { id: 36, name: '미라클 페인트', title_jp: 'ミラクルペイント' },
    { id: 86, name: '온 더 록', title_jp: 'on the rocks' },
    { id: 61, name: '휴대연화', title_jp: '携帯恋話' },
    { id: 45, name: '39뮤직!', title_jp: '39みゅーじっく！' },
    { id: 93, name: '푸르게 달려라!', title_jp: '青く駆けろ！' },
    { id: 64, name: '스텔라', title_jp: 'ステラ' },
    { id: 85, name: '레이아 - 리마인드', title_jp: 'Leia - Remind' },
    { id: 62, name: '잭팟 새드 걸', title_jp: 'ジャックポットサッドガール' },
    { id: 70, name: '멜티 랜드 나이트메어', title_jp: 'メルティランドナイトメア' },
    { id: 92, name: '소녀해부', title_jp: '乙女解剖' },
    { id: 52, name: '포테이토가 되어가', title_jp: 'potatoになっていく' },
    { id: 113, name: '롤링 걸', title_jp: 'ローリンガール' },
    { id: 99, name: '모어! 점프! 모어!', title_jp: 'モア！ジャンプ！モア！' },
    { id: 114, name: '겉과 속의 러버즈', title_jp: '裏表ラバーズ' },
    { id: 115, name: '언노운 마더 구스', title_jp: 'アンノウン・マザーグース' },
    { id: 108, name: '사랑받지 못해도 네가 있어', title_jp: '愛されなくても君がいる' },
    { id: 75, name: '갯나리 해저담', title_jp: 'ウミユリ海底譚' },
    { id: 55, name: '포워드', title_jp: 'Forward' },
    { id: 74, name: '혼자 놀이 엔비', title_jp: '独りんぼエンヴィー' },
    { id: 103, name: '무지갯빛 스토리즈', title_jp: 'ニジイロストーリーズ' },
    { id: 117, name: 'ODDS＆ENDS', title_jp: 'ODDS＆ENDS' },
    { id: 91, name: '드라마투르기', title_jp: 'ドラマツルギー' },
    { id: 46, name: '그린라이츠 세레나데', title_jp: 'グリーンライツ・セレナーデ' },
    { id: 87, name: '연애재판', title_jp: '恋愛裁判' },
    { id: 118, name: '*헬로, 플래닛.', title_jp: '＊ハロー、プラネット。' },
    { id: 110, name: '천본앵', title_jp: '千本桜' },
    { id: 100, name: 'ECHO', title_jp: 'ECHO' },
    { id: 88, name: '츄루리라·츄루리라·땃땃따!', title_jp: 'チュルリラ・チュルリラ・ダッダッダ！' },
    { id: 72, name: '블레스 유어 브레스', title_jp: 'ブレス・ユア・ブレス' },
    { id: 94, name: '너무 아파 아프고 싶어', title_jp: 'とても痛い痛がりたい' },
    { id: 97, name: '날이 개길 기다려', title_jp: '霽れを待つ' },
    { id: 119, name: '월즈 엔드 댄스홀', title_jp: 'ワールズエンド・ダンスホール' },
    { id: 109, name: '울려퍼져라', title_jp: 'ヒビカセ' },
    { id: 89, name: 'Color of Drops', title_jp: 'Color of Drops' },
    { id: 101, name: '라드 독스', title_jp: 'RAD DOGS' },
    { id: 107, name: '밀크 크라운 온 소네치카', title_jp: 'ミルククラウン・オン・ソーネチカ' },
    { id: 8, name: '타임머신', title_jp: 'タイムマシン' },
    { id: 15, name: '드롭 팝 캔디', title_jp: 'drop pop candy' },
    { id: 122, name: '포지티브☆댄스 타임', title_jp: 'ポジティブ☆ダンスタイム' },
    { id: 128, name: '브랜드 뉴 데이', title_jp: 'Brand New Day' },
    { id: 90, name: '끝없이 잿빛으로', title_jp: '限りなく灰色へ' },
    { id: 105, name: '원스 어폰 어 드림', title_jp: 'ワンスアポンアドリーム' },
    { id: 125, name: '보카 델라 베리타', title_jp: 'ボッカデラベリタ' },
    { id: 124, name: '미쿠미쿠하게 해줄게♪', title_jp: 'みくみくにしてあげる♪【してやんよ】' },
    { id: 95, name: '위풍당당', title_jp: '威風堂々' },
    { id: 96, name: '프롬 와이 투 와이', title_jp: 'from Y to Y' },
    { id: 131, name: '하츠네 미쿠의 격창', title_jp: '初音ミクの激唱' },
    { id: 112, name: '천사의 클로버', title_jp: '天使のクローバー' },
    { id: 106, name: '마음에 드시는 대로', title_jp: 'お気に召すまま' },
    { id: 123, name: '드리밍 츄츄', title_jp: 'どりーみんチュチュ' },
    { id: 116, name: '아이디 스마일', title_jp: 'アイディスマイル' },
    { id: 132, name: '「１」', title_jp: '「１」' },
    { id: 137, name: '꽃을 노래하다', title_jp: '花を唄う' },
    { id: 139, name: '밤을 달리다', title_jp: '夜に駆ける' },
    { id: 102, name: '유령 도쿄', title_jp: '幽霊東京' },
    { id: 126, name: '시네마', title_jp: 'シネマ' },
    { id: 138, name: '킹', title_jp: 'KING' },
    { id: 144, name: '사랑의 마테리얼', title_jp: 'アイノマテリアル' },
    { id: 120, name: '가지마', title_jp: 'いかないで' },
    { id: 121, name: '로미오와 신데렐라', title_jp: 'ロミオとシンデレラ' },
    { id: 151, name: '거품 미래', title_jp: '泡沫未来' },
    { id: 127, name: '톤데모 원더즈', title_jp: 'トンデモワンダーズ' },
    { id: 149, name: '카나데토모스소라', title_jp: 'カナデトモスソラ' },
    { id: 143, name: '트래픽 잼', title_jp: 'トラフィック・ジャム' },
    { id: 130, name: '프롬 도쿄', title_jp: 'フロムトーキョー' },
    { id: 156, name: '비트 이터', title_jp: 'Beat Eater' },
    { id: 135, name: '육조 년과 하룻밤 이야기', title_jp: '六兆年と一夜物語' },
    { id: 154, name: '지구 최후의 고백을', title_jp: '地球最後の告白を' },
    { id: 129, name: '비터 초코 데코레이션', title_jp: 'ビターチョコデコレーション' },
    { id: 165, name: '그랬지!!', title_jp: 'そうだった！！' },
    { id: 171, name: '아지랑이 데이즈', title_jp: 'カゲロウデイズ' },
    { id: 140, name: '아이스 드롭', title_jp: 'アイスドロップ' },
    { id: 166, name: '글로디 스테디 고!', title_jp: 'Glory Steady Go!' },
    { id: 136, name: '칠드런 레코드', title_jp: 'チルドレンレコード' },
    { id: 161, name: '매직 넘버', title_jp: 'magic number' },
    { id: 173, name: '유성의 펄스', title_jp: '流星のパルス' },
    { id: 111, name: '커틀러리', title_jp: 'カトラリー' },
    { id: 142, name: '재생', title_jp: '再生' },
    { id: 141, name: '군청찬가', title_jp: '群青讃歌' },
    { id: 179, name: '노심융해', title_jp: '炉心融解' },
    { id: 98, name: '로스트 원의 호곡', title_jp: 'ロストワンの号哭' },
    { id: 176, name: '머신건 포엠 돌', title_jp: 'マシンガンポエムドール' },
    { id: 145, name: '베놈', title_jp: 'ベノム' },
    { id: 175, name: '친애하는 도플갱어에게', title_jp: '拝啓ドッペルゲンガー' },
    { id: 134, name: '텔레캐스터 비보이', title_jp: 'テレキャスタービーボーイ' },
    { id: 150, name: '토키오 펑카', title_jp: 'トキヲ・ファンカ' },
    { id: 133, name: '악마가 춤추는 법', title_jp: '悪魔の踊り方' },
    { id: 152, name: '누군가의 심장이 될 수 있다면', title_jp: 'だれかの心臓になれたなら' },
    { id: 157, name: '마슈마리', title_jp: 'マシュマリー' },
    { id: 177, name: '오른 어깨의 나비', title_jp: '右肩の蝶' },
    { id: 148, name: '레이', title_jp: 'ray' },
    { id: 184, name: '헬로, 월드!', title_jp: 'Hello,world!' },
    { id: 185, name: '식 오브 하우스!', title_jp: 'しっくおぶはうす！' },
    { id: 160, name: '쇼타임 룰러', title_jp: 'ショウタイム・ルーラー' },
    { id: 172, name: '해피 할로윈', title_jp: 'Happy Halloween' },
    { id: 187, name: '로워', title_jp: 'ロウワー' },
    { id: 186, name: '천지개벽 신화', title_jp: '初音天地開闢神話' },
    { id: 167, name: '얼터 에고', title_jp: 'オルターエゴ' },
    { id: 159, name: '스테이지 오브 세카이', title_jp: 'STAGE OF SEKAI' },
    { id: 147, name: '꼭두각시 피에로', title_jp: 'からくりピエロ' },
    { id: 193, name: '월드와이드 원더', title_jp: 'ワールドワイドワンダー' },
    { id: 190, name: '악의 딸', title_jp: '悪ノ娘' },
    { id: 191, name: '악의 하인', title_jp: '悪ノ召使' },
    { id: 192, name: '떠나는 사람들의 왈츠', title_jp: '去り人達のワルツ' },
    { id: 197, name: '라스트 스코어', title_jp: 'ラストスコア' },
    { id: 183, name: '픽서', title_jp: 'フィクサー' },
    { id: 180, name: '미라이', title_jp: 'ミライ' },
    { id: 199, name: '고스트 룰', title_jp: 'ゴーストルール' },
    { id: 170, name: '빌런', title_jp: 'ヴィラン' },
    { id: 104, name: '샹드리용', title_jp: 'サンドリヨン' },
    { id: 169, name: '소녀 레이', title_jp: '少女レイ' },
    { id: 200, name: '갈란드', title_jp: 'ガランド' },
    { id: 162, name: '엔드마크에 희망과 눈물을 더하며', title_jp: 'エンドマークに希望と涙を添えて' },
    { id: 163, name: '디 엠페러', title_jp: 'the EmpErroR' },
    { id: 164, name: '돈 파이트 더 뮤직', title_jp: 'Don\'t Fight The Music' },
    { id: 178, name: '빙그레^^조사대의 테마', title_jp: 'にっこり^^調査隊のテーマ' },
    { id: 203, name: '트리콜로주', title_jp: 'トリコロージュ' },
    { id: 155, name: '심박수♯0822', title_jp: '心拍数♯0822' },
    { id: 204, name: '웃세와', title_jp: 'うっせぇわ' },
    { id: 205, name: '오도', title_jp: '踊' },
    { id: 206, name: '너의 색깔 마린 스노우', title_jp: '君色マリンスノウ' },
    { id: 181, name: '사랑해줘 사랑해줘 사랑해줘', title_jp: '愛して愛して愛して' },
    { id: 182, name: '플라이어!', title_jp: 'Flyer!' },
    { id: 207, name: '피키 피키', title_jp: 'Peaky Peaky' },
    { id: 215, name: '쥬다스', title_jp: 'ジウダス' },
    { id: 158, name: '난센스 문학', title_jp: 'ナンセンス文学' },
    { id: 188, name: '마음 예보', title_jp: '心予報' },
    { id: 208, name: '우리는 아직 언더그라운드', title_jp: '僕らまだアンダーグラウンド' },
    { id: 153, name: '미쿠', title_jp: 'Miku' },
    { id: 209, name: '메타모 리본', title_jp: 'メタモリボン' },
    { id: 174, name: '이얼 판클럽', title_jp: 'いーあるふぁんくらぶ' },
    { id: 210, name: '비와 페트라', title_jp: '雨とペトラ' },
    { id: 189, name: '노마드', title_jp: 'ノマド' },
    { id: 221, name: '마트료시카', title_jp: 'マトリョシカ' },
    { id: 220, name: '도넛홀', title_jp: 'ドーナツホール 2024' },
    { id: 219, name: '모래의 행성', title_jp: '砂の惑星' },
    { id: 216, name: '루카루카★나이트 피버', title_jp: 'ルカルカ★ナイトフィーバー' },
    { id: 222, name: '피아노×포르테×스캔들', title_jp: 'ピアノ×フォルテ×スキャンダル' },
    { id: 223, name: '천년의 독주가', title_jp: '千年の独奏歌' },
    { id: 224, name: '88☆彡', title_jp: '88☆彡' },
    { id: 227, name: 'ONESELF', title_jp: 'ONESELF' },
    { id: 195, name: 'PaⅢ.센세이션', title_jp: 'PaⅢ.SENSATION' },
    { id: 168, name: '달링 댄스', title_jp: 'ダーリンダンス' },
    { id: 196, name: '오더메이드', title_jp: 'オーダーメイド' },
    { id: 231, name: '아이덴티티', title_jp: 'アイデンティティ' },
    { id: 232, name: '푸른색 물감', title_jp: '青色絵具' },
    { id: 233, name: '코스모 스파이스', title_jp: 'コスモスパイス' },
    { id: 234, name: '도쿠가와 컵누들 금지령', title_jp: '徳川カップヌードル禁止令' },
    { id: 230, name: '샐러맨더', title_jp: 'サラマンダー' },
    { id: 211, name: '이프', title_jp: 'イフ' },
    { id: 238, name: '블랙★록 슈터', title_jp: 'ブラック★ロックシューター' },
    { id: 194, name: '망상감상대상연맹', title_jp: '妄想感傷代償連盟' },
    { id: 146, name: '리모컨', title_jp: 'リモコン' },
    { id: 239, name: '월광', title_jp: '月光' },
    { id: 201, name: '신의 뜻대로', title_jp: '神のまにまに' },
    { id: 244, name: '어웨이크 나우', title_jp: 'Awake Now' },
    { id: 245, name: '아훔의 비트', title_jp: '阿吽のビーツ' },
    { id: 248, name: '버그', title_jp: 'バグ' },
    { id: 198, name: '굿바이 선언', title_jp: 'グッバイ宣言' },
    { id: 213, name: '뱀파이어', title_jp: 'ヴァンパイア' },
    { id: 254, name: '미완성 찬가', title_jp: '未完成讃歌' },
    { id: 212, name: '별하늘의 멜로디', title_jp: '星空のメロディー' },
    { id: 229, name: '뇌장작렬 걸', title_jp: '脳漿炸裂ガール' },
    { id: 249, name: '우리들의 16bit 전쟁', title_jp: 'ぼくらの16bit戦争' },
    { id: 218, name: '메류', title_jp: 'メリュー' },
    { id: 246, name: '에일리언 에일리언', title_jp: 'エイリアンエイリアン' },
    { id: 217, name: '거리', title_jp: '街' },
    { id: 257, name: '번질번질', title_jp: 'てらてら' },
    { id: 251, name: '프로일라인=비블리오테카', title_jp: 'フロイライン＝ビブリォチカ' },
    { id: 240, name: '춤춰라 오케스트라', title_jp: '踊れオーケストラ' },
    { id: 264, name: '파라솔 사이다', title_jp: 'パラソルサイダー' },
    { id: 226, name: '로스트 앤 파운드', title_jp: 'ロストエンファウンド' },
    { id: 266, name: '와이와이', title_jp: 'YY' },
    { id: 274, name: '그래도 괜찮아', title_jp: 'それでもいいんだよ' },
    { id: 237, name: '너의 밤을 줘', title_jp: '君の夜をくれ' },
    { id: 273, name: '퓨처 이브', title_jp: 'フューチャー・イヴ' },
    { id: 236, name: '보이시즈', title_jp: 'Voices' },
    { id: 272, name: '게헨나', title_jp: 'ジェヘナ' },
    { id: 243, name: '칼크.', title_jp: 'Calc.' },
    { id: 280, name: '공허함을 부추기다', title_jp: '虚ろを扇ぐ' },
    { id: 235, name: '저니', title_jp: 'Journey' },
    { id: 289, name: '천성의 약함', title_jp: '天ノ弱' },
    { id: 288, name: '언해피 리프레인', title_jp: 'アンハッピーリフレイン' },
    { id: 277, name: '포니', title_jp: 'フォニイ' },
    { id: 256, name: '더블 래리어트', title_jp: 'ダブルラリアット' },
    { id: 284, name: '인비저블', title_jp: 'インビジブル' },
    { id: 225, name: '에고 록', title_jp: 'エゴロック' },
    { id: 278, name: '배드 ∞ 엔드 ∞ 나이트', title_jp: 'Bad ∞ End ∞ Night' },
    { id: 242, name: '토리노코시티', title_jp: 'トリノコシティ' },
    { id: 279, name: '여기는, 행복안심위원회입니다.', title_jp: 'こちら、幸福安心委員会です。' },
    { id: 253, name: '데이브레이크 프론트라인', title_jp: 'DAYBREAK FRONTLINE' },
    { id: 285, name: '아마라(대미래전뇌)', title_jp: 'ÅMARA(大未来電脳)' },
    { id: 252, name: '드림 플레이스', title_jp: 'DREAM PLACE' },
    { id: 270, name: '진흙 속에 피다', title_jp: '泥中に咲く' },
    { id: 292, name: '하나 둘 하고 셋에', title_jp: 'いちにのさんで' },
    { id: 262, name: '제국소녀', title_jp: '帝国少女' },
    { id: 265, name: '체인지 미', title_jp: 'Change me' },
    { id: 260, name: '라브카?', title_jp: 'ラブカ？' },
    { id: 259, name: '더 월', title_jp: 'the WALL' },
    { id: 304, name: '아이난데스', title_jp: 'Iなんです' },
    { id: 275, name: '파라디클로로벤젠', title_jp: 'パラジクロロベンゼン' },
    { id: 261, name: '별가루 유토피아', title_jp: '星屑ユートピア' },
    { id: 302, name: '후레이', title_jp: 'フレー' },
    { id: 271, name: '따뜻하다고', title_jp: 'あったかいと' },
    { id: 295, name: '플로트 플래너', title_jp: 'フロート・プランナー' },
    { id: 268, name: '논브레스 오블리주', title_jp: 'ノンブレス・オブリージュ' },
    { id: 269, name: '론리 유니버스', title_jp: 'ロンリーユニバース' },
    { id: 314, name: '양지의 찰나', title_jp: '陽だまりのセツナ' },
    { id: 267, name: '가사화', title_jp: '仮死化' },
    { id: 315, name: '왓츠 업 팝', title_jp: 'What\'s up? Pop!' },
    { id: 250, name: '썩은 외도와 초콜릿', title_jp: '腐れ外道とチョコレゐト' },
    { id: 255, name: '밤새도록 널 생각해', title_jp: '夜もすがら君想ふ' },
    { id: 298, name: '온라인 게임 폐인 슈프레히코어', title_jp: 'ネトゲ廃人シュプレヒコール' },
    { id: 296, name: '칸타렐라', title_jp: 'カンタレラ' },
    { id: 313, name: '프릴리 투모로우', title_jp: 'FREELY TOMORROW' },
    { id: 281, name: '변덕쟁이 메르시', title_jp: '気まぐれメルシィ' },
    { id: 294, name: '그것이 당신의 행복이라 할지라도', title_jp: 'それがあなたの幸せとしても' },
    { id: 303, name: '린짱 나우!', title_jp: 'リンちゃんなう！' },
    { id: 291, name: '펠레스', title_jp: 'フェレス' },
    { id: 311, name: '새벽과 반딧불이', title_jp: '夜明けと蛍' },
    { id: 282, name: '별하늘 오케스트라', title_jp: '星空オーケストラ' },
    { id: 310, name: '플라이웨이', title_jp: 'Flyway' },
    { id: 297, name: 'ph', title_jp: 'p.h.' },
    { id: 228, name: '굿바이', title_jp: 'Goodbye' },
    { id: 327, name: '스노우믹스♪', title_jp: 'SnowMix♪' },
    { id: 328, name: '세카이 쨩과 카후 쨩의 장보기 합소곡', title_jp: '星界ちゃんと可不ちゃんのおつかい合騒曲' },
    { id: 326, name: '천사의 날개.', title_jp: '天使の翼。' },
    { id: 247, name: '카피캣', title_jp: 'Copycat' },
    { id: 283, name: '레이니 스노우드롭', title_jp: 'レイニースノードロップ' },
    { id: 293, name: '아이러니', title_jp: 'アイロニ' },
    { id: 306, name: '1925', title_jp: '1925' },
    { id: 287, name: '나는, 우리는', title_jp: '私は、私達は' },
    { id: 316, name: '양이 한 마리', title_jp: 'ひつじがいっぴき' },
    { id: 286, name: '헬로, 워커', title_jp: 'Hello, Worker' },
    { id: 338, name: '웨어 쉘 위 고?', title_jp: 'Where shall we go?' },
    { id: 312, name: '마음', title_jp: 'ココロ' },
    { id: 305, name: '스트로보 라스트', title_jp: 'ストロボラスト' },
    { id: 214, name: '팔레트에는 네가 가득', title_jp: 'パレットには君がいっぱい' },
    { id: 202, name: 'Q', title_jp: 'Q' },
    { id: 329, name: '야미나베!!!!', title_jp: 'ヤミナベ!!!!' },
    { id: 320, name: 'Booo!', title_jp: 'Booo!' },
    { id: 331, name: '39', title_jp: '39' },
    { id: 333, name: '미스터. 쇼타임', title_jp: 'Mr. Showtime' },
    { id: 299, name: '에고이스트', title_jp: 'エゴイスト' },
    { id: 332, name: '에필로그에 넌 없어', title_jp: 'エピローグに君はいない' },
    { id: 263, name: '하이라이트', title_jp: 'Highlight' },
    { id: 321, name: '어트랙트 라이트', title_jp: 'アトラクトライト' },
    { id: 300, name: '잠자', title_jp: 'ザムザ' },
    { id: 335, name: '트래시 앤드 트래시!', title_jp: 'トラッシュ・アンド・トラッシュ！' },
    { id: 334, name: '뱀파이어 ∞ 파토스', title_jp: 'Vampire\'s ∞ pathoS' },
    { id: 336, name: '비 더 뮤직!', title_jp: 'Be The MUSIC!' },
    { id: 337, name: '미티어', title_jp: 'METEOR' },
    { id: 330, name: '인터뷰어', title_jp: 'インタビュア' },
    { id: 301, name: '나의 사랑은 헬파이어', title_jp: '私の恋はヘルファイア' },
    { id: 343, name: '스노우맨', title_jp: 'スノーマン' },
    { id: 258, name: '심해소녀', title_jp: '深海少女' },
    { id: 317, name: '마법 같은 뮤직!', title_jp: '魔法みたいなミュージック！' },
    { id: 351, name: '상생', title_jp: '相生' },
    { id: 359, name: '이름 없는 혁명', title_jp: '名も無き革命' },
    { id: 307, name: '어린이 전쟁', title_jp: 'おこちゃま戦争' },
    { id: 322, name: '끊임없는 남빛', title_jp: '絶え間なく藍色' },
    { id: 352, name: '목숨뿐', title_jp: '命ばっかり' },
    { id: 308, name: '복숭아색 열쇠', title_jp: 'ももいろの鍵' },
    { id: 353, name: '키티', title_jp: 'キティ' },
    { id: 323, name: '쾌청', title_jp: '快晴' },
    { id: 349, name: '악식녀 콘치타', title_jp: '悪食娘コンチータ' },
    { id: 350, name: '잠재우는 공주로부터의 선물', title_jp: '眠らせ姫からの贈り物' },
    { id: 347, name: '엔비자카의 재봉사', title_jp: '円尾坂の仕立屋' },
    { id: 348, name: '악덕의 저지먼트', title_jp: '悪徳のジャッジメント' },
    { id: 318, name: '쉐어링 더 월드', title_jp: 'Sharing The World' },
    { id: 354, name: '세츠나 트립', title_jp: 'セツナトリップ' },
    { id: 276, name: '샨티', title_jp: 'シャンティ' },
    { id: 364, name: '이터널 아리아', title_jp: 'エターナルアリア' },
    { id: 342, name: '블루 스타', title_jp: 'Blue Star' },
    { id: 324, name: '모형 정원의 코랄', title_jp: '箱庭のコラル' },
    { id: 370, name: '인생', title_jp: '人生' },
    { id: 362, name: '원더 스타일', title_jp: 'Wonder Style' },
    { id: 373, name: '하극상', title_jp: '下剋上' },
    { id: 346, name: '아아, 훌륭한 고양이의 삶', title_jp: '嗚呼、素晴らしきニャン生' },
    { id: 380, name: '스타더스트 메들리', title_jp: 'スターダストメドレー' },
    { id: 374, name: '팀메이트', title_jp: 'チームメイト' },
    { id: 339, name: '글로우', title_jp: 'glow' },
    { id: 340, name: '정말 멋진 6월이었습니다', title_jp: 'とても素敵な六月でした' },
    { id: 363, name: '언더워터', title_jp: 'UNDERWATER' },
    { id: 361, name: '두근 어질', title_jp: 'きゅうくらりん' },
    { id: 309, name: '애프터글로우', title_jp: 'Afterglow' },
    { id: 360, name: '태양계 디스코', title_jp: '太陽系デスコ' },
    { id: 382, name: '심박 페어링', title_jp: '心拍ペアリング' },
    { id: 345, name: '연극', title_jp: '演劇' },
    { id: 375, name: '별을 잇다', title_jp: '星を繋ぐ' },
    { id: 344, name: '뇌내혁명 걸', title_jp: '脳内革命ガール' },
    { id: 319, name: '디케이드', title_jp: 'Decade' },
    { id: 400, name: '우리들 스테인 버스터즈!', title_jp: '我らステインバスターズ！' },
    { id: 381, name: '신인류', title_jp: '新人類' },
    { id: 379, name: '즌다 파티 나잇', title_jp: 'ずんだパーリナイ' },
    { id: 399, name: '디스코 넘버.39', title_jp: 'Disco No.39' },
    { id: 395, name: '서머타임 레코드', title_jp: 'サマータイムレコード' },
    { id: 356, name: '리얼라이즈', title_jp: 'リアライズ' },
    { id: 386, name: '키라피피★키라피카', title_jp: 'キラピピ★キラピカ' },
    { id: 394, name: '보틀케이크', title_jp: 'ボトルケーキ' },
    { id: 358, name: '마음탓', title_jp: '心做し' },
    { id: 357, name: '블루 플래닛', title_jp: 'ブループラネット' },
    { id: 414, name: '히어로', title_jp: 'HERO' },
    { id: 408, name: '서커스 패닉!!!', title_jp: 'CIRCUS PANIC!!!' },
    { id: 355, name: '하얀 눈의 프린세스는', title_jp: '白い雪のプリンセスは' },
    { id: 393, name: '언락', title_jp: 'Un-Lock' },
    { id: 415, name: '럭키☆오브', title_jp: 'ラッキー☆オーブ' },
    { id: 366, name: 'NEO', title_jp: 'NEO' },
    { id: 368, name: '아임 마인', title_jp: 'アイムマイン' },
    { id: 372, name: '천악', title_jp: '天樂' },
    { id: 401, name: '뜻대로', title_jp: 'まにまに' },
    { id: 369, name: '멜랑콜릭', title_jp: 'メランコリック' },
    { id: 325, name: '돼지가 되어 yeah yeah', title_jp: '豚になってyeah yeah' },
    { id: 365, name: '사랑은 전쟁', title_jp: '恋は戦争' },
    { id: 412, name: '데빌이 아닌걸', title_jp: 'デビルじゃないもん' },
    { id: 367, name: '좋아하는 것만으로도 괜찮아요', title_jp: 'すきなことだけでいいです' },
    { id: 403, name: '츠가이코가라시', title_jp: '番凩' },
    { id: 385, name: '신 같네', title_jp: '神っぽいな' },
    { id: 390, name: '디어', title_jp: 'Dear' },
    { id: 421, name: '크레이지', title_jp: 'CR詠ZY' },
    { id: 425, name: '쿨 미 다운', title_jp: 'Cool Me Down' },
    { id: 377, name: '악역에게 키스신을', title_jp: '悪役にキスシーンを' },
    { id: 376, name: '제멋대로 공주', title_jp: '我儘姫' },
    { id: 383, name: '퍼포즈', title_jp: 'purpose' },
    { id: 429, name: '허그', title_jp: 'はぐ' },
    { id: 384, name: '트와일라잇 라이트', title_jp: 'トワイライトライト' },
    { id: 392, name: '춘람', title_jp: '春嵐' },
    { id: 406, name: '아키타입', title_jp: 'ARQETYPE' },
    { id: 426, name: '온 앤 온', title_jp: 'On&On' },
    { id: 391, name: '큐트한 그녀', title_jp: 'キュートなカノジョ' },
    { id: 397, name: '필라멘트 피버', title_jp: 'フィラメントフィーバー' },
    { id: 413, name: '안녕 프린세스', title_jp: 'さよならプリンセス' },
    { id: 398, name: '비욘드 더 웨이', title_jp: 'Beyond the way' },
    { id: 440, name: '쇼타임×오디언스', title_jp: 'ショウタイム×オーディエンス' },
    { id: 341, name: '난청계 남자가 쓰러지지 않아', title_jp: '難聴系男子が倒せない' },
    { id: 446, name: '오버 코드', title_jp: 'オーバーコード' },
    { id: 378, name: '슬로우 다우너', title_jp: 'スロウダウナー' },
    { id: 407, name: '첫사랑이 끝날 때', title_jp: '初めての恋が終わる時' },
    { id: 409, name: '25시의 정열', title_jp: '25時の情熱' },
    { id: 418, name: '금목서', title_jp: '金木犀' },
    { id: 439, name: '일천광년', title_jp: '一千光年' },
    { id: 432, name: '강풍 올백', title_jp: '強風オールバック' },
    { id: 433, name: '불장난', title_jp: 'ヒアソビ' },
    { id: 402, name: '엔비 베이비', title_jp: 'エンヴィーベイビー' },
    { id: 430, name: '『응앗앗。』', title_jp: '『んっあっあっ。』' },
    { id: 417, name: '텅 비어가', title_jp: 'くうになる' },
    { id: 438, name: '하이드 앤 시크', title_jp: 'ハイドアンド・シーク' },
    { id: 447, name: '폴른', title_jp: 'folern' },
    { id: 405, name: '못또!!!', title_jp: 'MOTTO!!!' },
    { id: 448, name: 'Sage', title_jp: 'Sage' },
    { id: 444, name: '심니몽(syndrome)', title_jp: '心泥夢(syndrome)' },
    { id: 452, name: '사이버펑크 데드 보이', title_jp: 'サイバーパンクデッドボーイ' },
    { id: 449, name: '마블블루.', title_jp: 'MarbleBlue.' },
    { id: 410, name: '마셜 맥시마이저', title_jp: 'マーシャル・マキシマイザー' },
    { id: 437, name: '응? 아아, 그래.', title_jp: 'え？あぁ、そう。' },
    { id: 435, name: '릴레이아우터', title_jp: 'リレイアウター' },
    { id: 461, name: '오도로보', title_jp: 'おどロボ' },
    { id: 411, name: '세계를 비추는 테트라드', title_jp: '世界を照らすテトラッド' },
    { id: 463, name: '해피 치트 데이', title_jp: 'ハッピーチートデー' },
    { id: 468, name: '열여섯 살의 심장', title_jp: '十六歳の心臓' },
    { id: 416, name: '림보', title_jp: 'limbo' },
    { id: 423, name: '레굴루스', title_jp: 'レグルス' },
    { id: 436, name: '고서저택 살인사건', title_jp: '古書屋敷殺人事件' },
    { id: 422, name: '점핀 오버!', title_jp: 'JUMPIN’ OVER !' },
    { id: 469, name: '래그 트레인', title_jp: 'ラグトレイン' },
    { id: 424, name: '인티그럴', title_jp: 'インテグラル' },
    { id: 455, name: '개쓰레기', title_jp: 'ド屑' },
    { id: 481, name: '명경지수', title_jp: '明鏡止水' },
    { id: 470, name: '첫 소리', title_jp: 'ハジメテノオト' },
    { id: 431, name: '플로스', title_jp: 'flos' },
    { id: 483, name: '아코토바', title_jp: 'アコトバ' },
    { id: 427, name: '유광, 1/f의 흔들림', title_jp: '幽光、1/fのゆらめき' },
    { id: 465, name: '양왕', title_jp: '嬢王' },
    { id: 434, name: '1000년 살고 있어', title_jp: '1000年生きてる' },
    { id: 456, name: '기망의 달', title_jp: '幾望の月' },
    { id: 404, name: '블렌더', title_jp: 'blender' },
    { id: 454, name: '일렉트릭 엔젤', title_jp: 'えれくとりっく・えんじぇぅ' },
    { id: 462, name: '레드 랜드 마커', title_jp: 'レッドランドマーカー' },
    { id: 467, name: '아이의노래', title_jp: 'あいのうた' },
    { id: 466, name: '가넷의 눈물', title_jp: 'ガーネットの涙' },
    { id: 485, name: '점점 빨라져', title_jp: 'だんだん早くなる' },
    { id: 492, name: '나는 비', title_jp: '私は雨' },
    { id: 441, name: '취한 줄을 모르고', title_jp: '酔いどれ知らず' },
    { id: 486, name: '오갸리나이저', title_jp: 'おぎゃりないざー' },
    { id: 496, name: '실버 콜렉터', title_jp: 'シルバーコレクター' },
    { id: 442, name: '스레스레', title_jp: 'すれすれ' },
    { id: 497, name: '열화', title_jp: '烈火' },
    { id: 503, name: '최종귀축 여동생 플랑드르 S', title_jp: '超最終鬼畜妹フランドール・Ｓ' },
    { id: 501, name: '배드 애플!!! 피처링.세카이', title_jp: 'Bad Apple!! feat.SEKAI' },
    { id: 502, name: '헬프 미, 에린ㄴㄴㄴ!!', title_jp: 'Help me, ERINNNNNN!!' },
    { id: 480, name: '장난기 기능', title_jp: 'おちゃめ機能' },
    { id: 428, name: '두근두근 제트코스터', title_jp: 'ときめきジェットコースター' },
    { id: 396, name: '도쿄 테디베어', title_jp: '東京テディベア' },
    { id: 451, name: '열이상', title_jp: '熱異常' },
    { id: 504, name: '아이 노 애뇌.', title_jp: 'I know 愛脳.' },
    { id: 482, name: '답 없는 인간이다!', title_jp: 'だめにんげんだ!' },
    { id: 450, name: '오페라! 스페이스 오페라!', title_jp: 'オペラ！スペースオペラ！' },
    { id: 458, name: '발묘', title_jp: '抜錨' },
    { id: 493, name: '오늘도 상쾌하게', title_jp: 'きょうもハレバレ' },
    { id: 457, name: '슈퍼노바', title_jp: 'Supernova' },
    { id: 507, name: '엠퍼플', title_jp: 'エンパープル' },
    { id: 512, name: '합성하는 미래', title_jp: '合成するミライ' },
    { id: 460, name: '리더', title_jp: 'LEADER' },
    { id: 494, name: '팝핀캔디☆피버!', title_jp: 'ポッピンキャンディ☆フィーバー！' },
    { id: 471, name: '울트라 씨', title_jp: 'ULTRA C' },
    { id: 487, name: '괜찮으신가요?', title_jp: 'ダイジョブですか？' },
    { id: 472, name: '처단하겠다AAAAA!', title_jp: '成敗いたAAAAAす！' },
    { id: 443, name: '사과팔이 물거품 소녀', title_jp: '林檎売りの泡沫少女' },
    { id: 517, name: '메리 고 라운드', title_jp: 'メリーゴーラウンド' },
    { id: 473, name: '마인드 브랜드', title_jp: 'マインドブランド' },
    { id: 515, name: '의학', title_jp: 'イガク' },
    { id: 516, name: '여기저기 데이트 씨', title_jp: 'あちこちデートさん' },
    { id: 474, name: '키라', title_jp: 'キラー' },
    { id: 522, name: '웨이브', title_jp: 'WAVE' },
    { id: 526, name: '혜성의 은하', title_jp: '彗星ノ銀河' },
    { id: 519, name: '여름밤의 노래', title_jp: '夏夜ノ唄' },
    { id: 506, name: '퀸', title_jp: 'QUEEN' },
    { id: 525, name: '안테나39', title_jp: 'アンテナ39' },
    { id: 475, name: '달라!!!', title_jp: 'ちがう!!!' },
    { id: 495, name: '슈퍼히어로', title_jp: 'スーパーヒーロー' },
    { id: 529, name: '컬처', title_jp: 'カルチャ' },
    { id: 532, name: '레이어 노트', title_jp: 'レイヤーノート' },
    { id: 524, name: '그럼에도 우리는 노래하는 것을 그만두지 않아', title_jp: 'それでも僕らは歌うことをやめない' },
    { id: 527, name: '언포이즌', title_jp: 'Unpoison' },
    { id: 489, name: '열풍', title_jp: '熱風' },
    { id: 477, name: '모자이크 롤 (Reloaded)', title_jp: 'モザイクロール (Reloaded)' },
    { id: 531, name: '메스머라이저', title_jp: 'メズマライザー' },
    { id: 511, name: '키사라기 어텐션', title_jp: '如月アテンション' },
    { id: 541, name: '메인 캐릭터', title_jp: 'メインキャラクター' },
    { id: 505, name: '콜보이', title_jp: 'コールボーイ' },
    { id: 523, name: '너와 나의 레조넌스', title_jp: 'きみとぼくのレゾナンス' },
    { id: 533, name: '전생사과', title_jp: '転生林檎' },
    { id: 542, name: '블랙잭', title_jp: 'Blackjack' },
    { id: 476, name: '섀도우 섀도우', title_jp: 'Shadow Shadow' },
    { id: 543, name: '생명성 신드롬', title_jp: '生命性シンドロウム' },
    { id: 549, name: '둔갑의 꽃', title_jp: '化けの花' },
    { id: 530, name: '캣 푸드', title_jp: 'キャットフード' },
    { id: 488, name: '메모리아', title_jp: 'メモリア' },
    { id: 545, name: '정수리', title_jp: '脳天' },
    { id: 478, name: '퓨얼', title_jp: 'フューエル' },
    { id: 546, name: '그 소리가 울린다면', title_jp: 'その音が鳴るなら' },
    { id: 544, name: '망상 아스파탐', title_jp: '妄想アスパルテーム' },
    { id: 491, name: '캣 러빙', title_jp: 'キャットラビング' },
    { id: 548, name: '나의 신님', title_jp: 'ぼくのかみさま' },
    { id: 553, name: '패리', title_jp: 'パリィ' },
    { id: 518, name: '금성', title_jp: 'みかぼし' },
    { id: 500, name: '여화에 넋을 잃고', title_jp: '余花にみとれて' },
    { id: 569, name: '시크릿 시커', title_jp: 'シークレット・シーカー' },
    { id: 498, name: '달려라! 저 멀리! 닿아라!', title_jp: 'はしる! とおく! とどく!' },
    { id: 557, name: '꽃에 빠지다', title_jp: '花溺れ' },
    { id: 573, name: '시작의 미래', title_jp: 'はじまりの未来' },
    { id: 499, name: '혼돈 부기', title_jp: '混沌ブギ' },
    { id: 562, name: '앙헬', title_jp: 'アンヘル' },
    { id: 561, name: '프로토 디스코', title_jp: 'プロトディスコ' },
    { id: 513, name: '체인지', title_jp: 'CH4NGE' },
    { id: 554, name: 'snooze', title_jp: 'snooze' },
    { id: 534, name: '월드 램프 쉐이드 [reunion]', title_jp: 'ワールド・ランプシェード [reunion]' },
    { id: 558, name: '것이다', title_jp: 'のだ' },
    { id: 556, name: '사이하테', title_jp: 'サイハテ' },
    { id: 484, name: '헨스포스', title_jp: 'Henceforth' },
    { id: 581, name: '중병격발 보이', title_jp: '厨病激発ボーイ' },
    { id: 508, name: '헤이븐', title_jp: 'ヘイヴン' },
    { id: 565, name: '여름에 투명', title_jp: '夏に透明' },
    { id: 566, name: '판다 히어로', title_jp: 'パンダヒーロー' },
    { id: 567, name: '쥐었다가 펼쳐서 나찰과 송장', title_jp: '結ンデ開イテ羅刹ト骸' },
    { id: 576, name: '파이어 댄스', title_jp: 'ファイアダンス' },
    { id: 564, name: '그곳에 있는, 빛.', title_jp: 'そこに在る、光。' },
    { id: 579, name: '월더스', title_jp: 'Worlders' },
    { id: 575, name: '펀!!', title_jp: 'FUN!!' },
    { id: 547, name: '종언도피행', title_jp: '終焉逃避行' },
    { id: 577, name: '스마일*심포니', title_jp: 'スマイル*シンフォニー' },
    { id: 574, name: '스토리', title_jp: 'SToRY' },
    { id: 593, name: '크리스털 스노우', title_jp: 'クリスタルスノウ' },
    { id: 578, name: '헬로 세카이', title_jp: 'ハローセカイ' },
    { id: 582, name: '안티 유', title_jp: 'アンチユー' },
    { id: 587, name: '룰 북', title_jp: 'ルルブ' },
    { id: 555, name: '퓨전', title_jp: 'フュージョン' },
    { id: 490, name: '루머', title_jp: 'ルーマー' },
    { id: 536, name: '파이어◎플라워 (Rerec)', title_jp: 'Fire◎Flower (Rerec)' },
    { id: 580, name: '초승달 스텝', title_jp: '三日月ステップ' },
    { id: 521, name: '오버라이드', title_jp: 'オーバーライド' },
    { id: 604, name: '패키지드', title_jp: 'Packaged' },
    { id: 509, name: '라이어 댄서', title_jp: 'ライアーダンサー' },
    { id: 588, name: '플래닛 히어로', title_jp: 'プラネットヒーロー' },
    { id: 520, name: '투명 엘레지', title_jp: '透明エレジー' },
    { id: 596, name: 'D/N/A', title_jp: 'D/N/A' },
    { id: 603, name: '도레미파 론도', title_jp: 'ドレミファロンド' },
    { id: 605, name: 'Sympathy', title_jp: 'Sympathy' },
    { id: 594, name: '콜!!!', title_jp: 'Call!!' },
    { id: 591, name: '요시하라 라멘토', title_jp: '吉原ラメント 再来盤' },
    { id: 590, name: '맨해튼', title_jp: 'マンハッタン' },
    { id: 592, name: '퀸 오브 하트', title_jp: 'クイーンオブハート' },
    { id: 589, name: '발레리코', title_jp: 'バレリーコ' },
    { id: 537, name: '꽃에 바람', title_jp: '花に風' },
    { id: 606, name: '수어사이드 퍼레이드', title_jp: 'スーサイドパレヱド' },
    { id: 608, name: '별우주 멜랑콜리아', title_jp: '星宙メランコリア' },
    { id: 607, name: '회전하는 하늘 토끼', title_jp: '回る空うさぎ' },
    { id: 538, name: '올 세이브 챌린지', title_jp: 'オールセーブチャレンジ' },
    { id: 624, name: '치르노의 퍼펙트 산수학원', title_jp: 'チルノのパーフェクトさんすう学園' },
    { id: 623, name: '동방☆원더랜드', title_jp: 'とうほう☆ワンダーランド' },
    { id: 622, name: '초나이트 오브 나이츠', title_jp: '超ナイト・オブ・ナイツ' },
    { id: 540, name: '허무 씨', title_jp: '虚無さん' },
    { id: 620, name: '사마', title_jp: '紗痲' },
    { id: 510, name: '실패작 소녀', title_jp: '失敗作少女' },
    { id: 626, name: '피쉬 앤 Tips', title_jp: 'フィッシュアンドTips' },
    { id: 619, name: '커넥팅', title_jp: 'Connecting' },
    { id: 595, name: '엔비 캣워크', title_jp: 'エンヴィキャットウォーク' },
    { id: 539, name: '일레븐스', title_jp: 'イレヴンス' },
    { id: 634, name: '광선가', title_jp: '光線歌' },
    { id: 627, name: '테토리스', title_jp: 'テトリス' },
    { id: 625, name: '이 실없이 멋진 세계는, 나를 위해 있어', title_jp: 'このふざけた素晴らしき世界は、僕の為にある' },
    { id: 628, name: '모니터링', title_jp: 'モニタリング' },
    { id: 633, name: '정원사의 말에 따르면', title_jp: '庭師のおはなしによると' },
    { id: 445, name: '트와일라이트 멜로디', title_jp: 'Twilight Melody' },
    { id: 552, name: '매@지컬☆큐트! 러브 ♥ 샷!', title_jp: 'M@GICAL☆CURE! LOVE ♥ SHOT!' },
    { id: 387, name: '헬로 빌더', title_jp: 'Hello Builder' },
    { id: 420, name: '이메지너리 러브 스토리', title_jp: 'imaginary love story' },
    { id: 464, name: '인터갈라틱 바운드', title_jp: 'Intergalactic Bound' },
    { id: 637, name: '웃으면 좋다 아이가!', title_jp: '笑えたらえーやん！' },
    { id: 560, name: '아이리드', title_jp: 'アイリッド' },
    { id: 646, name: '투명한 팔레트', title_jp: '透明なパレット' },
    { id: 636, name: '익스플로어', title_jp: 'エクスプロウル' },
    { id: 635, name: '있는 그대로의 이야기를', title_jp: 'ありのままのストーリーを' },
    { id: 644, name: '살다', title_jp: '生きる' },
    { id: 638, name: '꽃잎, 그것에 얽힌 음성', title_jp: '花弁、それにまつわる音声' },
    { id: 639, name: '마리오네트 댄서', title_jp: 'マリオネットダンサー' },
    { id: 648, name: '라이프 윌 체인지', title_jp: 'Life Will Change' },
    { id: 583, name: '액셀러레이트', title_jp: 'アクセラレイト' },
    { id: 632, name: '서지', title_jp: 'Surges' },
    { id: 655, name: '릴리라라', title_jp: 'リリィララ' },
    { id: 647, name: 'SAN치 직장', title_jp: 'SAN値直葬' },
    { id: 572, name: '장식하며', title_jp: '飾って' },
    { id: 654, name: '러스트러스', title_jp: 'ラストラス' },
    { id: 649, name: '잘 있어 천국 다시 와줘 지옥', title_jp: 'サヨナラ天国また来て地獄' },
    { id: 629, name: '8.32', title_jp: '8.32' },
    { id: 650, name: '그 여름이 포화한다.', title_jp: 'あの夏が飽和する。' },
    { id: 645, name: '심해시티 언더그라운드', title_jp: '深海シティアンダーグラウンド' },
    { id: 656, name: '블러드 돌', title_jp: 'ブラッドドール' },
    { id: 571, name: '가짜인간40호', title_jp: '偽物人間40号' },
    { id: 585, name: '펜타토닉', title_jp: 'ペンタトニック' },
    { id: 559, name: '춤춰라', title_jp: 'おどりゃんせ' },
    { id: 666, name: '소녀A', title_jp: '少女A' },
    { id: 621, name: '도쿄 서머 세션', title_jp: '東京サマーセッション' },
    { id: 663, name: '비너스', title_jp: 'ヴィーナス' },
    { id: 672, name: '하우 투 세계정복', title_jp: 'ハウトゥー世界征服' },
    { id: 669, name: '원점', title_jp: 'げんてん' },
    { id: 664, name: '사람 마니아', title_jp: '人マニア' },
    { id: 667, name: '(무)책임집합체', title_jp: '㋰責任集合体' },
    { id: 551, name: '로스트 엄브렐라', title_jp: 'ロストアンブレラ' },
    { id: 651, name: '화이트 해피', title_jp: 'ホワイトハッピー' },
    { id: 668, name: '네크라튠 서커스', title_jp: 'ネクラチューンサーカス' },
    { id: 652, name: '남자친구의 주드', title_jp: 'カレシのジュード' },
    { id: 653, name: '파멜라', title_jp: 'パメラ' },
    { id: 570, name: '스타', title_jp: 'スター' },
    { id: 659, name: '당신의 하늘이 운다면', title_jp: 'あなたの空が泣くのなら' },
    { id: 677, name: '아벨리아', title_jp: 'アベリア' },
    { id: 601, name: '루마', title_jp: 'ルマ' },
    { id: 665, name: '로켓 사이다', title_jp: 'ロケットサイダー' },
    { id: 597, name: '그 그림의 이름은', title_jp: 'その絵の名前は' },
    { id: 678, name: '금시계', title_jp: '金時計' },
    { id: 600, name: '나아가라', title_jp: '征け' },
    { id: 684, name: '파이터', title_jp: 'ファイター' },
    { id: 584, name: '이마와노키와', title_jp: 'IMAWANOKIWA' },
    { id: 671, name: '괴수가 되고 싶어', title_jp: '怪獣になりたい' },
    { id: 691, name: '0.0000034', title_jp: '0.0000034' }
];
